# CREATE A DICIONARY WITH THE DATA FROM THE MAIN FILE RELATED TO THE HEROES
heroes_dict = {
        'Ainz Ooal Gown' : {
    'name': 'Ainz Ooal Gown',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\ainz ooal gown.png',
    'sig_img': 'images\\items\\ainz ooal gown sigitem.png',
    'sig': 'Staff Of Ainz Ooal Gown',
    'skills': {
        'skill_1': 'Fallen Down',
        'skill_2': ' Magic Caster',
        'skill_3': ' The Goal of All Life Is Death',
        'skill_4': ' Steady Preparations',
        'skill_5': 'Cash Items'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Alaro' : {
    'name': 'Alaro',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\alaro.png',
    'sig_img': 'images\\items\\alaro sigitem.png',
    'sig': 'MaulerS Horn',
    'skills': {
        'skill_1': ' Unwanted Surprises',
        'skill_2': ' Incognito Mode',
        'skill_3': ' Dummy Double',
        'skill_4': ' Snooping Ambush',
        'skill_5': 'All Too Easy'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Albedo' : {
    'name': 'Albedo',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Tank',
    'img': 'images\\heroes\\albedo.png',
    'sig_img': 'images\\items\\albedo sigitem.png',
    'sig': 'Ginnungagap',
    'skills': {
        'skill_1': 'Ginnungagap',
        'skill_2': ' Black Guard',
        'skill_3': ' Shield Lord',
        'skill_4': ' Hermes Trismegistus',
        'skill_5': 'Guardian Overseer'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Alna' : {
    'name': 'Alna',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\alna.png',
    'sig_img': 'images\\items\\alna sigitem.png',
    'sig': 'Frostbite',
    'skills': {
        'skill_1': 'Winter War Cry',
        'skill_2': 'Freezing Pierce',
        'skill_3': 'Winter\'s Call',
        'skill_4': 'Frozen Fury',
        'skill_5': 'Unrelenting Heart'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Anasta' : {
    'name': 'Anasta',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\anasta.png',
    'sig_img': 'images\\items\\anasta sigitem.png',
    'sig': 'Windcleaver',
    'skills': {
        'skill_1': 'Spiral Cleaver',
        'skill_2': 'Confrontation',
        'skill_3': 'Shattered Shields',
        'skill_4': 'Mauler\'s Prowess',
        'skill_5': 'Inextinguishable Might'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Angelo' : {
    'name': 'Angelo',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\angelo.png',
    'sig_img': 'images\\items\\angelo sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': ' Love and Peace',
        'skill_2': ' Encourage',
        'skill_3': ' Restoration',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FFFFFF',
    'rarity': 'Legendary',
    },
    'Ankhira' : {
    'name': 'Ankhira',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\ankhira.png',
    'sig_img': 'images\\items\\ankhira sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': ' Venomous Bile',
        'skill_2': ' Corrosion',
        'skill_3': ' Coccoon',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FF0000',
    'rarity': 'Legendary',
    },
    'Anoki' : {
    'name': 'Anoki',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Control',
    'img': 'images\\heroes\\anoki.png',
    'sig_img': 'images\\items\\anoki sigitem.png',
    'sig': 'Blood Guards Warhorn',
    'skills': {
        'skill_1': ' Savage Stampede',
        'skill_2': ' Raging Stomp',
        'skill_3': ' Born To Lead',
        'skill_4': ' Horn of War',
        'skill_5': 'War Fury'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Antandra' : {
    'name': 'Antandra',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\antandra.png',
    'sig_img': 'images\\items\\antandra sigitem.png',
    'sig': 'Dances-In-Blood',
    'skills': {
        'skill_1': 'Fury Strike',
        'skill_2': 'Mark of the Wild',
        'skill_3': 'Piercing Assault',
        'skill_4': 'Knockdown',
        'skill_5': 'Unconquerable'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Arden' : {
    'name': 'Arden',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\arden.png',
    'sig_img': 'images\\items\\arden sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Force of Nature',
        'skill_2': 'Entangling Roots',
        'skill_3': 'Shield of Thorns',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#779A71',
    'rarity': 'Legendary',
    },
    'Arkadios' : {
    'name': 'Arkadios',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\arkadios.png',
    'sig_img': 'images\\items\\arkadios sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Gloomy Cloud',
        'skill_2': 'Hunters Glare',
        'skill_3': '',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FF0000',
    'rarity': 'Common',
    },
    'Arthur' : {
    'name': 'Arthur',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Tank',
    'img': 'images\\heroes\\arthur.png',
    'sig_img': 'images\\items\\arthur sigitem.png',
    'sig': 'Excalibur',
    'skills': {
        'skill_1': 'Smite',
        'skill_2': 'Excaliburs Fury',
        'skill_3': 'Kings Blessing',
        'skill_4': 'Shield of Honor',
        'skill_5': 'Battle Rally'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Astar' : {
    'name': 'Astar',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Regen',
    'img': 'images\\heroes\\astar.png',
    'sig_img': 'images\\items\\astar sigitem.png',
    'sig': 'Excalibur',
    'skills': {
        'skill_1': 'Life Sparks',
        'skill_2': 'Lanterns Flame',
        'skill_3': 'Flame Seeds',
        'skill_4': 'Aura of Fire',
        'skill_5': 'Burning Wave'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Athalia' : {
    'name': 'Athalia',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\athalia.png',
    'sig_img': 'images\\items\\athalia sigitem.png',
    'sig': 'The Sin Purgers',
    'skills': {
        'skill_1': 'Divine Fury',
        'skill_2': 'Judgement',
        'skill_3': 'Purging Frenzy',
        'skill_4': 'Protection',
        'skill_5': 'Bloodless'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Audrae' : {
    'name': 'Audrae',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\audrae.png',
    'sig_img': 'images\\items\\audrae sigitem.png',
    'sig': 'Stellar Bow And Arrow',
    'skills': {
        'skill_1': 'Cosmic Shower',
        'skill_2': 'Cosmic Assault',
        'skill_3': 'Cores Protection',
        'skill_4': 'Focus Fire',
        'skill_5': 'Astral Enclosure'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Awakened Baden' : {
    'name': 'Awakened Baden',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\awakened baden.png',
    'sig_img': 'images\\items\\awakened baden sigitem.png',
    'sig': 'Wilting Thorns',
    'skills': {
        'skill_1': 'Blight Clone',
        'skill_2': 'Razor Leaf',
        'skill_3': 'Vine Lash',
        'skill_4': 'Clone Link',
        'skill_5': 'Razor Leaf'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Awakened Brutus' : {
    'name': 'Awakened Brutus',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\awakened brutus.png',
    'sig_img': 'images\\items\\awakened brutus sigitem.png',
    'sig': 'Montain Breaker',
    'skills': {
        'skill_1': 'Shattered Montain',
        'skill_2': 'Rank Breaker',
        'skill_3': 'Fury Blow',
        'skill_4': 'Unyielding Spirit',
        'skill_5': 'Rank Breaker'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Awakened Ezizh' : {
    'name': 'Awakened Ezizh',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\awakened ezizh.png',
    'sig_img': 'images\\items\\awakened ezizh sigitem.png',
    'sig': 'Infernal Pauldron',
    'skills': {
        'skill_1': 'Nightmare\'s Descent',
        'skill_2': 'Dephts of Darkness',
        'skill_3': 'Mind Flay',
        'skill_4': 'Nightmare Arc',
        'skill_5': 'Dephts of Darkness'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Awakened Solise' : {
    'name': 'Awakened Solise',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Regen',
    'img': 'images\\heroes\\awakened solise.png',
    'sig_img': 'images\\items\\awakened solise sigitem.png',
    'sig': 'Crescent Staff',
    'skills': {
        'skill_1': 'Clouds\' Fall',
        'skill_2': 'Water\'s Call',
        'skill_3': 'Spirit Animation',
        'skill_4': 'Torrential Link',
        'skill_5': 'Water\'s Call'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Awakened Talene' : {
    'name': 'Awakened Talene',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\awakened talene.png',
    'sig_img': 'images\\items\\awakened talene sigitem.png',
    'sig': 'Heart of the Phoenix',
    'skills': {
        'skill_1': 'A New Dawn',
        'skill_2': 'Blade of Resurgence',
        'skill_3': 'Everlasting Flame',
        'skill_4': 'Wings of Fire',
        'skill_5': 'Blade of Resurgence'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Awakened Thane' : {
    'name': 'Awakened Thane',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\awakened thane.png',
    'sig_img': 'images\\items\\awakened thane sigitem.png',
    'sig': 'The Lotus Blade',
    'skills': {
        'skill_1': 'Wind\'s Edge',
        'skill_2': 'Maelstrom',
        'skill_3': 'Dueling Blades',
        'skill_4': 'Winds of Fury',
        'skill_5': 'Maelstrom'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Baden' : {
    'name': 'Baden',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\baden.png',
    'sig_img': 'images\\items\\baden sigitem.png',
    'sig': 'Spear Of Decay',
    'skills': {
        'skill_1': 'Phantom Assassin',
        'skill_2': 'Phantom Strike',
        'skill_3': 'Spectral Onslaught',
        'skill_4': 'Spectral Surge',
        'skill_5': 'Phantom Force'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Belinda' : {
    'name': 'Belinda',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\belinda.png',
    'sig_img': 'images\\items\\belinda sigitem.png',
    'sig': 'Staff Of Light',
    'skills': {
        'skill_1': 'Divine Light',
        'skill_2': 'Divine Retribution',
        'skill_3': 'Brilliance',
        'skill_4': 'Blessing',
        'skill_5': 'Gift of Heaven'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Bloodsnarl' : {
    'name': 'Bloodsnarl',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\bloodsnarl.png',
    'sig_img': 'images\\items\\bloodsnarl sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Raging Spiral',
        'skill_2': 'Hurl',
        'skill_3': '',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FF0000',
    'rarity': 'Common',
    },
    'Brutus' : {
    'name': 'Brutus',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Tank',
    'img': 'images\\heroes\\brutus.png',
    'sig_img': 'images\\items\\brutus sigitem.png',
    'sig': 'Rends-The-Weak',
    'skills': {
        'skill_1': 'Whirlwind',
        'skill_2': 'Roar',
        'skill_3': 'Brutal Defiance',
        'skill_4': 'Last Gasp',
        'skill_5': 'Upsurge'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Canisa and Ruke' : {
    'name': 'Canisa and Ruke',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Tank',
    'img': 'images\\heroes\\canisa and ruke.png',
    'sig_img': 'images\\items\\canisa and ruke sigitem.png',
    'sig': 'Avenging Chain',
    'skills': {
        'skill_1': 'Lightning Lock',
        'skill_2': 'Wound Reversal',
        'skill_3': 'Howl of Fury',
        'skill_4': 'Cage of Fire',
        'skill_5': 'Chain Reach'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Cecilia' : {
    'name': 'Cecilia',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\cecilia.png',
    'sig_img': 'images\\items\\cecilia sigitem.png',
    'sig': 'Sacred Book Of Cleansing',
    'skills': {
        'skill_1': 'Judgement Day',
        'skill_2': 'Blade of Purification',
        'skill_3': 'Atonement',
        'skill_4': 'Devil Trap',
        'skill_5': 'Repentance'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Daimon' : {
    'name': 'Daimon',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Tank',
    'img': 'images\\heroes\\daimon.png',
    'sig_img': 'images\\items\\daimon sigitem.png',
    'sig': 'Stitchy',
    'skills': {
        'skill_1': 'Soul Feast',
        'skill_2': 'Blood Shield',
        'skill_3': 'Inanimate Companion',
        'skill_4': 'Forbidden Power',
        'skill_5': 'Soul Sunder'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Desira' : {
    'name': 'Desira',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Regen',
    'img': 'images\\heroes\\desira.png',
    'sig_img': 'images\\items\\desira sigitem.png',
    'sig': 'Shell Of Treason',
    'skills': {
        'skill_1': 'Sirens Call',
        'skill_2': 'Hatreds Mark',
        'skill_3': 'Oceanic Shield',
        'skill_4': 'Oceanic Mist',
        'skill_5': 'Concealing Mist'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Dreaf' : {
    'name': 'Dreaf',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\dreaf.png',
    'sig_img': 'images\\items\\dreaf sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Noxious Seeds',
        'skill_2': 'Piercing Spines',
        'skill_3': '',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#779A71',
    'rarity': 'Common',
    },
    'Drez' : {
    'name': 'Drez',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\drez.png',
    'sig_img': 'images\\items\\drez sigitem.png',
    'sig': 'Ivory Piercer',
    'skills': {
        'skill_1': 'Deadly Ambush',
        'skill_2': 'Bloody Evisceration',
        'skill_3': 'Tactical Retreat',
        'skill_4': 'Rabid Slice',
        'skill_5': 'Hunters Shield'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Eironn' : {
    'name': 'Eironn',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\eironn.png',
    'sig_img': 'images\\items\\eironn sigitem.png',
    'sig': 'Elemental Blades',
    'skills': {
        'skill_1': 'Elemental Surge',
        'skill_2': 'Twin Force',
        'skill_3': 'Vortex',
        'skill_4': 'Sylvan Oath',
        'skill_5': 'Chill'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Eletha' : {
    'name': 'Eletha',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\eletha.png',
    'sig_img': 'images\\items\\eletha sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Piercing Blow',
        'skill_2': 'Bloody Frenzy',
        'skill_3': '',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#779A71',
    'rarity': 'Common',
    },
    'Elijah & Lailah' : {
    'name': 'Elijah & Lailah',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\elijah & lailah.png',
    'sig_img': 'images\\items\\elijah & lailah sigitem.png',
    'sig': 'Bonding Feathers',
    'skills': {
        'skill_1': 'Hope',
        'skill_2': 'Grace',
        'skill_3': 'Cleanse',
        'skill_4': 'Unity',
        'skill_5': 'Blessed Binding'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Eluard' : {
    'name': 'Eluard',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\eluard.png',
    'sig_img': 'images\\items\\eluard sigitem.png',
    'sig': 'Golden Visage',
    'skills': {
        'skill_1': 'Sanctimony',
        'skill_2': 'Divine Miracle',
        'skill_3': 'Prayer of Protection',
        'skill_4': 'Judgment',
        'skill_5': 'Judgement'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Eorin' : {
    'name': 'Eorin',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\eorin.png',
    'sig_img': 'images\\items\\eorin sigitem.png',
    'sig': 'Parasitic Spear',
    'skills': {
        'skill_1': 'Combined Spear',
        'skill_2': 'Weakspot Mark',
        'skill_3': 'Poisonous Mushroom',
        'skill_4': 'Stacking Spores',
        'skill_5': 'Parasitic Spear'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Estrilda' : {
    'name': 'Estrilda',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\estrilda.png',
    'sig_img': 'images\\items\\estrilda sigitem.png',
    'sig': 'Banner Of Rayne',
    'skills': {
        'skill_1': 'Joust',
        'skill_2': 'Royal Charge',
        'skill_3': 'Inspire',
        'skill_4': 'Ridicule',
        'skill_5': 'In Command'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Ezio' : {
    'name': 'Ezio',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\ezio.png',
    'sig_img': 'images\\items\\ezio sigitem.png',
    'sig': 'Hidden Blade',
    'skills': {
        'skill_1': 'Eagle Vision',
        'skill_2': 'Final Retribution',
        'skill_3': 'Smoke Bomb',
        'skill_4': 'Evasion',
        'skill_5': 'Assassins Target'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Ezizh' : {
    'name': 'Ezizh',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\ezizh.png',
    'sig_img': 'images\\items\\ezizh sigitem.png',
    'sig': 'Armor Of Ruin',
    'skills': {
        'skill_1': 'Fissure',
        'skill_2': 'Feeble Mind',
        'skill_3': 'Horrify',
        'skill_4': 'Mental Fury',
        'skill_5': 'Immolate'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Fane' : {
    'name': 'Fane',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\fane.png',
    'sig_img': 'images\\items\\fane sigitem.png',
    'sig': 'Bone Hook',
    'skills': {
        'skill_1': 'Malign Judgement',
        'skill_2': 'Prisoner of Despair',
        'skill_3': 'Soul Impaler',
        'skill_4': 'Unscrupulous Jailer',
        'skill_5': 'Prison Master'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Fawkes' : {
    'name': 'Fawkes',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Control',
    'img': 'images\\heroes\\fawkes.png',
    'sig_img': 'images\\items\\fawkes sigitem.png',
    'sig': 'The Soul Prision',
    'skills': {
        'skill_1': 'Purification',
        'skill_2': 'Abate',
        'skill_3': 'Confine',
        'skill_4': 'Silver Bolt',
        'skill_5': 'Purged Perseverance'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Ferael' : {
    'name': 'Ferael',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\ferael.png',
    'sig_img': 'images\\items\\ferael sigitem.png',
    'sig': 'HaunterS Hand',
    'skills': {
        'skill_1': 'Nether Blaze',
        'skill_2': 'Accursed Arrow',
        'skill_3': 'Terrorize',
        'skill_4': 'Corrupted Spirit',
        'skill_5': 'Anguished Spirit'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Flora' : {
    'name': 'Flora',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\flora.png',
    'sig_img': 'images\\items\\flora sigitem.png',
    'sig': 'The Serene Branch',
    'skills': {
        'skill_1': 'Sea of Flowers',
        'skill_2': 'Airborne',
        'skill_3': 'Swoop',
        'skill_4': 'Rejuvenation',
        'skill_5': 'Diminish'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Framton' : {
    'name': 'Framton',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\framton.png',
    'sig_img': 'images\\items\\framton sigitem.png',
    'sig': 'Blaze Vambraces',
    'skills': {
        'skill_1': 'Blazing Meteor',
        'skill_2': 'Burning Vengeance',
        'skill_3': 'Fists of Fire',
        'skill_4': 'Flaming Feast',
        'skill_5': 'Eternal Flame'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Geralt' : {
    'name': 'Geralt',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\geralt.png',
    'sig_img': 'images\\items\\geralt sigitem.png',
    'sig': 'Wolf School Medallion',
    'skills': {
        'skill_1': 'Potion Buff',
        'skill_2': 'Whril',
        'skill_3': 'Rend',
        'skill_4': 'Battle Signs',
        'skill_5': 'Wolf\'s Sword'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Golus' : {
    'name': 'Golus',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Control',
    'img': 'images\\heroes\\golus.png',
    'sig_img': 'images\\items\\golus sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Collision',
        'skill_2': 'Outburst',
        'skill_3': 'Unwavering Will',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FF0000',
    'rarity': 'Legendary',
    },
    'Gorvo' : {
    'name': 'Gorvo',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Tank',
    'img': 'images\\heroes\\gorvo.png',
    'sig_img': 'images\\items\\gorvo sigitem.png',
    'sig': 'Gate Crasher',
    'skills': {
        'skill_1': 'Battle Cry',
        'skill_2': 'Dive Bomb',
        'skill_3': 'Shell Shock',
        'skill_4': 'Shell Shield',
        'skill_5': 'Nature\'s Shield'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Granit' : {
    'name': 'Granit',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Tank',
    'img': 'images\\heroes\\granit.png',
    'sig_img': 'images\\items\\granit sigitem.png',
    'sig': 'DesertS Core',
    'skills': {
        'skill_1': 'Sand Vortex',
        'skill_2': 'Earth Tremors',
        'skill_3': 'Stone Skin',
        'skill_4': 'Earthen Resilience',
        'skill_5': 'Earthly Rejuvenation'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Grezhul' : {
    'name': 'Grezhul',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Tank',
    'img': 'images\\heroes\\grezhul.png',
    'sig_img': 'images\\items\\grezhul sigitem.png',
    'sig': 'The Slayer Blades',
    'skills': {
        'skill_1': 'Reanimate',
        'skill_2': 'Demonic Assault',
        'skill_3': 'Shadow Shield',
        'skill_4': 'Deathly Protection',
        'skill_5': 'Reanimation'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Gwyneth' : {
    'name': 'Gwyneth',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\gwyneth.png',
    'sig_img': 'images\\items\\gwyneth sigitem.png',
    'sig': 'Shooting Star',
    'skills': {
        'skill_1': 'Divine Arrow',
        'skill_2': 'Flaming Arrows',
        'skill_3': 'Lightning Arrows',
        'skill_4': 'Strength In Numbers',
        'skill_5': 'Focus Fire'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Haelus' : {
    'name': 'Haelus',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\haelus.png',
    'sig_img': 'images\\items\\haelus sigitem.png',
    'sig': 'The Peerless Obelisk',
    'skills': {
        'skill_1': 'Laws of Creation',
        'skill_2': 'Divine Projection',
        'skill_3': 'Sphere of Craftsmanship',
        'skill_4': 'Born Blessings',
        'skill_5': 'Concealing Force'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Hendrik' : {
    'name': 'Hendrik',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Tank',
    'img': 'images\\heroes\\hendrik.png',
    'sig_img': 'images\\items\\hendrik sigitem.png',
    'sig': 'The Bastion',
    'skills': {
        'skill_1': 'Crippling Blow',
        'skill_2': 'Shield Bash',
        'skill_3': 'Sacrificial Shield',
        'skill_4': 'Standfast',
        'skill_5': 'Steadfast'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Hodgkin' : {
    'name': 'Hodgkin',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Tank',
    'img': 'images\\heroes\\hodgkin.png',
    'sig_img': 'images\\items\\hodgkin sigitem.png',
    'sig': 'Soul Devourers',
    'skills': {
        'skill_1': 'The Immortal',
        'skill_2': 'Soul Devourer',
        'skill_3': 'Jolly Roger',
        'skill_4': 'Revilers Defiance',
        'skill_5': 'Pirates Greed'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Hogan' : {
    'name': 'Hogan',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Control',
    'img': 'images\\heroes\\hogan.png',
    'sig_img': 'images\\items\\hogan sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Knights Fury',
        'skill_2': 'Zealous Strike',
        'skill_3': 'Unwavering Will',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FFFFFF',
    'rarity': 'Legendary',
    },
    'Ira' : {
    'name': 'Ira',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\ira.png',
    'sig_img': 'images\\items\\ira sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Hail of Arrows',
        'skill_2': 'Glacial Arrow',
        'skill_3': 'Piercing Arrow',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#779A71',
    'rarity': 'Legendary',
    },
    'Isabella' : {
    'name': 'Isabella',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\isabella.png',
    'sig_img': 'images\\items\\isabella sigitem.png',
    'sig': 'Tome Of The Dead',
    'skills': {
        'skill_1': 'Decimation',
        'skill_2': 'Void Barrage',
        'skill_3': 'Psi Reap',
        'skill_4': 'Surge',
        'skill_5': 'Lightning Barrage'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Izold' : {
    'name': 'Izold',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Tank',
    'img': 'images\\heroes\\izold.png',
    'sig_img': 'images\\items\\izold sigitem.png',
    'sig': 'Doomstriker Syringe',
    'skills': {
        'skill_1': 'Toxic Transfusion',
        'skill_2': 'Noxious Blast',
        'skill_3': 'Needle Strike',
        'skill_4': 'Hypodermic Healing',
        'skill_5': 'Lethal Dose'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Joan of Arc' : {
    'name': 'Joan of Arc',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\joan of arc.png',
    'sig_img': 'images\\items\\joan of arc sigitem.png',
    'sig': 'Iris Standard',
    'skills': {
        'skill_1': 'Stand Firm',
        'skill_2': 'Waving Standard',
        'skill_3': 'Standard Shield',
        'skill_4': 'Standard Barrier',
        'skill_5': 'Standard Protection'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Joker' : {
    'name': 'Joker',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\joker.png',
    'sig_img': 'images\\items\\joker sigitem.png',
    'sig': 'Vile Sword',
    'skills': {
        'skill_1': 'Maeigaon',
        'skill_2': 'Adverse Reaction',
        'skill_3': 'Concentrated Fire',
        'skill_4': 'All-Out Attack',
        'skill_5': 'Widespread Attack'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Kalene' : {
    'name': 'Kalene',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\kalene.png',
    'sig_img': 'images\\items\\kalene sigitem.png',
    'sig': 'Necrohound',
    'skills': {
        'skill_1': 'Necrohound',
        'skill_2': 'Eternal Lifeblood',
        'skill_3': 'Ephemeral Spirits',
        'skill_4': 'Blood Ritual',
        'skill_5': 'Blood Feast'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Kaz' : {
    'name': 'Kaz',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\kaz.png',
    'sig_img': 'images\\items\\kaz sigitem.png',
    'sig': 'The NightS Kiss',
    'skills': {
        'skill_1': 'Assassinate',
        'skill_2': 'Triple Strike',
        'skill_3': 'Evasive Strike',
        'skill_4': 'Feline Finesse',
        'skill_5': 'Elude'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Kelthur' : {
    'name': 'Kelthur',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\kelthur.png',
    'sig_img': 'images\\items\\kelthur sigitem.png',
    'sig': 'The Harvester',
    'skills': {
        'skill_1': 'Blades of Fury',
        'skill_2': 'Retaliation',
        'skill_3': 'Displace',
        'skill_4': 'Ethereal Resurgence',
        'skill_5': 'Blood Sap'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Khasos' : {
    'name': 'Khasos',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\khasos.png',
    'sig_img': 'images\\items\\khasos sigitem.png',
    'sig': 'Chief Choppers',
    'skills': {
        'skill_1': 'Spinning Obliteration',
        'skill_2': 'Concentration',
        'skill_3': 'Throwing Axe',
        'skill_4': 'Rabid Thirst',
        'skill_5': 'Precision'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Khazard' : {
    'name': 'Khazard',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Control',
    'img': 'images\\heroes\\khazard.png',
    'sig_img': 'images\\items\\khazard sigitem.png',
    'sig': 'The Frigid Aura',
    'skills': {
        'skill_1': 'Frozen Mist',
        'skill_2': 'Glacial Shards',
        'skill_3': 'Frozen Beam',
        'skill_4': 'Frost Serpent',
        'skill_5': 'Frozen Curse'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Kren' : {
    'name': 'Kren',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\kren.png',
    'sig_img': 'images\\items\\kren sigitem.png',
    'sig': '“Hot Stuff” & “Lady”',
    'skills': {
        'skill_1': 'Bomb Voyage',
        'skill_2': 'Enshrouding Bomb',
        'skill_3': 'Old Pal',
        'skill_4': 'Concussive Blast',
        'skill_5': 'Potent Firepower'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Leofric' : {
    'name': 'Leofric',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\leofric.png',
    'sig_img': 'images\\items\\leofric sigitem.png',
    'sig': 'Shadow Mastiff Cane',
    'skills': {
        'skill_1': 'Shadow Mastiff',
        'skill_2': 'Hell Wyrms',
        'skill_3': 'Unmasked Horror',
        'skill_4': 'Perfect Disguise',
        'skill_5': 'Heart of Malice'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Leonardo' : {
    'name': 'Leonardo',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Control',
    'img': 'images\\heroes\\leonardo.png',
    'sig_img': 'images\\items\\leonardo sigitem.png',
    'sig': 'The Creator',
    'skills': {
        'skill_1': 'Work of Art',
        'skill_2': 'Art Attack',
        'skill_3': 'Renaissance Cannon',
        'skill_4': 'Evacuation',
        'skill_5': 'The Machinist'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Lorsan' : {
    'name': 'Lorsan',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\lorsan.png',
    'sig_img': 'images\\items\\lorsan sigitem.png',
    'sig': 'Wind Keeper',
    'skills': {
        'skill_1': 'Tempest',
        'skill_2': 'Inner Sight',
        'skill_3': 'Gale Force',
        'skill_4': 'Wind Ward',
        'skill_5': 'Fate'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Lucius' : {
    'name': 'Lucius',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Regen',
    'img': 'images\\heroes\\lucius.png',
    'sig_img': 'images\\items\\lucius sigitem.png',
    'sig': 'The Winged Protector',
    'skills': {
        'skill_1': 'Heavens Protection',
        'skill_2': 'Divine Strike',
        'skill_3': 'Divine Blessing',
        'skill_4': 'Blessed Shield',
        'skill_5': 'Divine Purge'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Lucretia' : {
    'name': 'Lucretia',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\lucretia.png',
    'sig_img': 'images\\items\\lucretia sigitem.png',
    'sig': 'Dark Star',
    'skills': {
        'skill_1': 'Ungodly Defiance',
        'skill_2': 'Hellfire',
        'skill_3': 'Deathwish',
        'skill_4': 'Twin Terrors',
        'skill_5': 'Animus'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Lyca' : {
    'name': 'Lyca',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\lyca.png',
    'sig_img': 'images\\items\\lyca sigitem.png',
    'sig': 'Starfall',
    'skills': {
        'skill_1': 'Star Shot',
        'skill_2': 'Rapid Arrows',
        'skill_3': 'Awe',
        'skill_4': 'Foes Fragility',
        'skill_5': 'Vision of Stars'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Mehira' : {
    'name': 'Mehira',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Control',
    'img': 'images\\heroes\\mehira.png',
    'sig_img': 'images\\items\\mehira sigitem.png',
    'sig': 'Lash Of Submission',
    'skills': {
        'skill_1': 'Mesmerize',
        'skill_2': 'Whiplash',
        'skill_3': 'Infatuation',
        'skill_4': 'Hellspawn',
        'skill_5': 'Carnal Bliss'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Melusina' : {
    'name': 'Melusina',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\melusina.png',
    'sig_img': 'images\\items\\melusina sigitem.png',
    'sig': 'Staff Of Domination',
    'skills': {
        'skill_1': 'Dropping By',
        'skill_2': 'Treacherous Treehouse',
        'skill_3': 'Alchemic Witchcraft',
        'skill_4': 'Soul Pilfer',
        'skill_5': 'Soul Taker'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Merek' : {
    'name': 'Merek',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\merek.png',
    'sig_img': 'images\\items\\merek sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Divine Blessing',
        'skill_2': 'Divine Vitality',
        'skill_3': '',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FFFFFF',
    'rarity': 'Common',
    },
    'Merlin' : {
    'name': 'Merlin',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Regen',
    'img': 'images\\heroes\\merlin.png',
    'sig_img': 'images\\items\\merlin sigitem.png',
    'sig': 'DestinyS Sight',
    'skills': {
        'skill_1': 'Destiny Foreseen',
        'skill_2': 'Magical Amelioration',
        'skill_3': 'Karmic Law',
        'skill_4': 'Guardian Owl',
        'skill_5': 'Shared Destiny'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Mezoth' : {
    'name': 'Mezoth',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Tank',
    'img': 'images\\heroes\\mezoth.png',
    'sig_img': 'images\\items\\mezoth sigitem.png',
    'sig': 'Blood And Gore',
    'skills': {
        'skill_1': 'Devour',
        'skill_2': 'Abyssal Butchery',
        'skill_3': 'Demonic Hunger',
        'skill_4': 'Carnivorous Lust',
        'skill_5': 'Virulent Greed'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Mirael' : {
    'name': 'Mirael',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\mirael.png',
    'sig_img': 'images\\items\\mirael sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Fire Phoenix',
        'skill_2': 'Fireball',
        'skill_3': 'Flame Shield',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FFFFFF',
    'rarity': 'Legendary',
    },
    'Mishka' : {
    'name': 'Mishka',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Control',
    'img': 'images\\heroes\\mishka.png',
    'sig_img': 'images\\items\\mishka sigitem.png',
    'sig': 'Bear Talons',
    'skills': {
        'skill_1': 'Werebear',
        'skill_2': 'Dire Wolves',
        'skill_3': 'Call of the Wild',
        'skill_4': 'Natural Rejuvenation',
        'skill_5': 'Natural Defense'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Morael' : {
    'name': 'Morael',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\morael.png',
    'sig_img': 'images\\items\\morael sigitem.png',
    'sig': 'Heart Of Zohra',
    'skills': {
        'skill_1': 'Cosmic Field',
        'skill_2': 'Cosmic Motion',
        'skill_3': 'Cosmic Fusion',
        'skill_4': 'Celestial Blessing',
        'skill_5': 'Astral Fortune'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Morrow' : {
    'name': 'Morrow',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Control',
    'img': 'images\\heroes\\morrow.png',
    'sig_img': 'images\\items\\morrow sigitem.png',
    'sig': 'Abyssal Tome',
    'skills': {
        'skill_1': 'Eye of Evil',
        'skill_2': 'Binding Terror',
        'skill_3': 'Demonic Murmurs',
        'skill_4': 'Abyssal Retribution',
        'skill_5': 'Murder of Crows'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Mortas' : {
    'name': 'Mortas',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Regen',
    'img': 'images\\heroes\\mortas.png',
    'sig_img': 'images\\items\\mortas sigitem.png',
    'sig': 'Deception',
    'skills': {
        'skill_1': 'Empowerment',
        'skill_2': 'Greed',
        'skill_3': 'Blood Pact',
        'skill_4': 'Devilish Deal',
        'skill_5': 'Trickery'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Morvus' : {
    'name': 'Morvus',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\morvus.png',
    'sig_img': 'images\\items\\morvus sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Sharpshooter',
        'skill_2': 'Concussive Grenade',
        'skill_3': 'Lethal Focus',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FFFFFF',
    'rarity': 'Legendary',
    },
    'Mulan' : {
    'name': 'Mulan',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\mulan.png',
    'sig_img': 'images\\items\\mulan sigitem.png',
    'sig': 'Magnolian Blade',
    'skills': {
        'skill_1': 'Rider\'s Wrath',
        'skill_2': 'Flashing Steel',
        'skill_3': 'Formidable Fortress',
        'skill_4': 'Rentless Pursuit',
        'skill_5': 'Deffense to Offense'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Nakoruru' : {
    'name': 'Nakoruru',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\nakoruru.png',
    'sig_img': 'images\\items\\nakoruru sigitem.png',
    'sig': 'Chichi-Ushi',
    'skills': {
        'skill_1': 'Running Chest Jab',
        'skill_2': 'Kamui Rimuse',
        'skill_3': 'Shichikapu Etu',
        'skill_4': 'Kamui Mutsube',
        'skill_5': 'Heavy Slash'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Nara' : {
    'name': 'Nara',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\nara.png',
    'sig_img': 'images\\items\\nara sigitem.png',
    'sig': 'Bloodshed',
    'skills': {
        'skill_1': 'Butchery',
        'skill_2': 'Dismember',
        'skill_3': 'Impale',
        'skill_4': 'Terrify',
        'skill_5': 'Looming Death'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Nemora' : {
    'name': 'Nemora',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Regen',
    'img': 'images\\heroes\\nemora.png',
    'sig_img': 'images\\items\\nemora sigitem.png',
    'sig': 'The Blossom Spear',
    'skills': {
        'skill_1': 'Wild Wonder',
        'skill_2': 'Beguile',
        'skill_3': 'Mother Nature',
        'skill_4': 'Life Force',
        'skill_5': 'Natures Touch'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Nevanthi' : {
    'name': 'Nevanthi',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Regen',
    'img': 'images\\heroes\\nevanthi.png',
    'sig_img': 'images\\items\\nevanthi sigitem.png',
    'sig': 'Deflecting Sprouts',
    'skills': {
        'skill_1': 'Nature\'s Flourish',
        'skill_2': 'Connecting Branches',
        'skill_3': 'Natural Gifts',
        'skill_4': 'Verdant Shade',
        'skill_5': 'Deflecting Sprouts'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Niru' : {
    'name': 'Niru',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\niru.png',
    'sig_img': 'images\\items\\niru sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Death Call',
        'skill_2': 'Life Leech',
        'skill_3': 'Soul Reaper',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#026B5C',
    'rarity': 'Legendary',
    },
    'Numisu' : {
    'name': 'Numisu',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Regen',
    'img': 'images\\heroes\\numisu.png',
    'sig_img': 'images\\items\\numisu sigitem.png',
    'sig': 'Mask Of Visions',
    'skills': {
        'skill_1': 'Resonating Blast',
        'skill_2': 'Rejuvenating Totem',
        'skill_3': 'Offensive Totem',
        'skill_4': 'Fanaticism',
        'skill_5': 'Totem Master'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Oden' : {
    'name': 'Oden',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\oden.png',
    'sig_img': 'images\\items\\oden sigitem.png',
    'sig': 'Void Gazer',
    'skills': {
        'skill_1': 'Soul Burn',
        'skill_2': 'Void Lightning',
        'skill_3': 'Eviction',
        'skill_4': 'Eye of Evil',
        'skill_5': 'Vengeful Fury'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Ogi' : {
    'name': 'Ogi',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Control',
    'img': 'images\\heroes\\ogi.png',
    'sig_img': 'images\\items\\ogi sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Resilience',
        'skill_2': 'Ground Fissure',
        'skill_3': 'Bombard',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#779A71',
    'rarity': 'Legendary',
    },
    'Oku' : {
    'name': 'Oku',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Tank',
    'img': 'images\\heroes\\oku.png',
    'sig_img': 'images\\items\\oku sigitem.png',
    'sig': 'Chitinous Shield',
    'skills': {
        'skill_1': 'Trembling Mountain',
        'skill_2': 'Vengeful Grievance',
        'skill_3': 'Beetle Bash',
        'skill_4': 'Besieging Fist',
        'skill_5': 'Forests Restoration'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Orthros' : {
    'name': 'Orthros',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Tank',
    'img': 'images\\heroes\\orthros.png',
    'sig_img': 'images\\items\\orthros sigitem.png',
    'sig': 'The Heavenly Vision',
    'skills': {
        'skill_1': 'Time Suspension',
        'skill_2': 'Time Trap',
        'skill_3': 'Inertia',
        'skill_4': 'Celestial Vigor',
        'skill_5': 'Time Warp'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Oscar' : {
    'name': 'Oscar',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\oscar.png',
    'sig_img': 'images\\items\\oscar sigitem.png',
    'sig': 'Exquisite Table Knife',
    'skills': {
        'skill_1': 'Aura of Haste',
        'skill_2': 'Fine Cuts',
        'skill_3': 'Slice and Dice',
        'skill_4': 'Unfazed',
        'skill_5': 'Uninvited Guest'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Palmer' : {
    'name': 'Palmer',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\palmer.png',
    'sig_img': 'images\\items\\palmer sigitem.png',
    'sig': 'The Lotus Blade',
    'skills': {
        'skill_1': 'Wind\'s Edge',
        'skill_2': 'Maelstrom',
        'skill_3': 'Dueling Blades',
        'skill_4': 'Winds of Fury',
        'skill_5': 'Maelstrom'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Peggy' : {
    'name': 'Peggy',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Regen',
    'img': 'images\\heroes\\peggy.png',
    'sig_img': 'images\\items\\peggy sigitem.png',
    'sig': 'Gorgeous Conch',
    'skills': {
        'skill_1': 'Duty Bound',
        'skill_2': 'Royal Scroll',
        'skill_3': 'Royal Guards',
        'skill_4': 'Royal Marksmen',
        'skill_5': 'Battle Hardened'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Pippa' : {
    'name': 'Pippa',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\pippa.png',
    'sig_img': 'images\\items\\pippa sigitem.png',
    'sig': 'Branch Of Verdure',
    'skills': {
        'skill_1': 'Pippas Imitation',
        'skill_2': 'Pippas Pandemonium',
        'skill_3': 'Transmogrification',
        'skill_4': 'Astral Shift',
        'skill_5': 'Pippa Power'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Prince of Persia' : {
    'name': 'Prince of Persia',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\prince of persia.png',
    'sig_img': 'images\\items\\prince of persia sigitem.png',
    'sig': 'Dagger Of Time',
    'skills': {
        'skill_1': 'Sands of Time',
        'skill_2': 'Tempest of Agony',
        'skill_3': 'Wall Dive Attack',
        'skill_4': 'Concentrated Force',
        'skill_5': 'Bounding Agility'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Queen' : {
    'name': 'Queen',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\queen.png',
    'sig_img': 'images\\items\\queen sigitem.png',
    'sig': 'Sanction',
    'skills': {
        'skill_1': 'Stationary Drifter',
        'skill_2': 'Freidyne',
        'skill_3': 'Attack & Defend',
        'skill_4': 'Ms. Post-Apocalyptic Raider',
        'skill_5': 'Edge of Death'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Raine' : {
    'name': 'Raine',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\raine.png',
    'sig_img': 'images\\items\\raine sigitem.png',
    'sig': 'Dueling Blasters',
    'skills': {
        'skill_1': 'Cripple',
        'skill_2': 'Barrage',
        'skill_3': 'Lock On',
        'skill_4': 'Exploit',
        'skill_5': 'Helping Hand'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Raku' : {
    'name': 'Raku',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\raku.png',
    'sig_img': 'images\\items\\raku sigitem.png',
    'sig': 'Elemental Slingshot',
    'skills': {
        'skill_1': 'Acorn Cannon',
        'skill_2': 'Entangling Shot',
        'skill_3': 'Peckish',
        'skill_4': 'Rakus Mark',
        'skill_5': 'Troublemaker'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Respen' : {
    'name': 'Respen',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\respen.png',
    'sig_img': 'images\\items\\respen sigitem.png',
    'sig': 'Mark Of The Wild',
    'skills': {
        'skill_1': 'Wind Spiral',
        'skill_2': 'Feathered Fury',
        'skill_3': 'Winged Attack',
        'skill_4': 'Winged Protection',
        'skill_5': 'Kindred Spirits'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Rigby' : {
    'name': 'Rigby',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Tank',
    'img': 'images\\heroes\\rigby.png',
    'sig_img': 'images\\items\\rigby sigitem.png',
    'sig': 'Oak Barrel',
    'skills': {
        'skill_1': 'Barrel Bomb',
        'skill_2': 'Fire Breath',
        'skill_3': 'Drunken Frenzy',
        'skill_4': 'Well Rested',
        'skill_5': 'Fiery Demise'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Rosaline' : {
    'name': 'Rosaline',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\rosaline.png',
    'sig_img': 'images\\items\\rosaline sigitem.png',
    'sig': 'Servitude',
    'skills': {
        'skill_1': 'Motivation',
        'skill_2': 'Crazy Crockery',
        'skill_3': 'Afternoon Tea',
        'skill_4': 'Spring Cleaning',
        'skill_5': 'Servitude'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Rowan' : {
    'name': 'Rowan',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\rowan.png',
    'sig_img': 'images\\items\\rowan sigitem.png',
    'sig': 'The Gold Chime',
    'skills': {
        'skill_1': 'Dazzle',
        'skill_2': 'Avian Assault',
        'skill_3': 'Healthy Supplies',
        'skill_4': 'Damage Control',
        'skill_5': 'Thirsty Work'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Safiya' : {
    'name': 'Safiya',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\safiya.png',
    'sig_img': 'images\\items\\safiya sigitem.png',
    'sig': 'Supremacy',
    'skills': {
        'skill_1': 'Falling Sun',
        'skill_2': 'Scattered Bolt',
        'skill_3': 'Static Field',
        'skill_4': 'Spectral Disruption',
        'skill_5': 'Arcane Power'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Salaki' : {
    'name': 'Salaki',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\salaki.png',
    'sig_img': 'images\\items\\salaki sigitem.png',
    'sig': 'Staff of Sacrifice',
    'skills': {
        'skill_1': 'Flagellant\'s Flame',
        'skill_2': 'Withering Winds',
        'skill_3': 'Frightening Forcefield',
        'skill_4': 'Death Defferred',
        'skill_5': 'Inheritance'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Satrana' : {
    'name': 'Satrana',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\satrana.png',
    'sig_img': 'images\\items\\satrana sigitem.png',
    'sig': 'Blazing Ember',
    'skills': {
        'skill_1': 'Firedance',
        'skill_2': 'Flutter Flame',
        'skill_3': 'Fireseeds',
        'skill_4': 'Overflow',
        'skill_5': 'Mark of the Fox'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Saurus' : {
    'name': 'Saurus',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\saurus.png',
    'sig_img': 'images\\items\\saurus sigitem.png',
    'sig': 'Hope\'S Edge',
    'skills': {
        'skill_1': 'Phase Form',
        'skill_2': 'War Strike',
        'skill_3': 'Burst Strikes',
        'skill_4': 'Tenacity',
        'skill_5': 'Warriors Valor'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Saveas' : {
    'name': 'Saveas',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\saveas.png',
    'sig_img': 'images\\items\\saveas sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Burning Acrimony',
        'skill_2': 'Bloodied Spear',
        'skill_3': 'Sacrificial Sustenance',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FF0000',
    'rarity': 'Legendary',
    },
    'Scarlet' : {
    'name': 'Scarlet',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\scarlet.png',
    'sig_img': 'images\\items\\scarlet sigitem.png',
    'sig': 'Arcane Stabilizer',
    'skills': {
        'skill_1': 'Dark Rage',
        'skill_2': 'Shaded Corruption',
        'skill_3': 'Arcane Absorption',
        'skill_4': 'Dark Aura',
        'skill_5': 'Lingering Power'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Seirus' : {
    'name': 'Seirus',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Tank',
    'img': 'images\\heroes\\seirus.png',
    'sig_img': 'images\\items\\seirus sigitem.png',
    'sig': 'Tidemaker',
    'skills': {
        'skill_1': 'Abhorrent Torrent',
        'skill_2': 'Deluge',
        'skill_3': 'Oceans Blessing',
        'skill_4': 'Free Flow',
        'skill_5': 'Sea Lord'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Sezis' : {
    'name': 'Sezis',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Control',
    'img': 'images\\heroes\\sezis.png',
    'sig_img': 'images\\items\\sezis sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Grim Swipe',
        'skill_2': 'Swiping Swing',
        'skill_3': '',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#026B5C',
    'rarity': 'Common',
    },
    'Shemira' : {
    'name': 'Shemira',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\shemira.png',
    'sig_img': 'images\\items\\shemira sigitem.png',
    'sig': 'The Spirit Orb',
    'skills': {
        'skill_1': 'Tortured Souls',
        'skill_2': 'Soul Siphon',
        'skill_3': 'Silence',
        'skill_4': 'Wrath',
        'skill_5': 'Twisted Torture'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Silas' : {
    'name': 'Silas',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\silas.png',
    'sig_img': 'images\\items\\silas sigitem.png',
    'sig': 'Augmentation Blades',
    'skills': {
        'skill_1': 'Injected Fury',
        'skill_2': 'Stimulated Rage',
        'skill_3': 'Double Dosage',
        'skill_4': 'Healing Haze',
        'skill_5': 'Adrenaline Shot'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Silvina' : {
    'name': 'Silvina',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\silvina.png',
    'sig_img': 'images\\items\\silvina sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Fatal Strike',
        'skill_2': 'Abyssal Shield',
        'skill_3': 'First Blood',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#026B5C',
    'rarity': 'Legendary',
    },
    'Skreg' : {
    'name': 'Skreg',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Tank',
    'img': 'images\\heroes\\skreg.png',
    'sig_img': 'images\\items\\skreg sigitem.png',
    'sig': 'Long Fang',
    'skills': {
        'skill_1': 'Beast of Burden',
        'skill_2': 'Brute Force',
        'skill_3': 'Ironskin',
        'skill_4': 'Stampede',
        'skill_5': 'Beast Rider'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Skriath' : {
    'name': 'Skriath',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\skriath.png',
    'sig_img': 'images\\items\\skriath sigitem.png',
    'sig': 'Wisdom Keeper',
    'skills': {
        'skill_1': 'Desert Vortex',
        'skill_2': 'Death from Above',
        'skill_3': 'Sandstorm',
        'skill_4': 'Critical Insight',
        'skill_5': 'Boulder Blast'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Solise' : {
    'name': 'Solise',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Control',
    'img': 'images\\heroes\\solise.png',
    'sig_img': 'images\\items\\solise sigitem.png',
    'sig': 'Floral Cloak Of Hope',
    'skills': {
        'skill_1': 'Blossom Fall',
        'skill_2': 'Floral Disruption',
        'skill_3': 'Floral Specter',
        'skill_4': 'Forests Blessing',
        'skill_5': 'Flower Power'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Sonja' : {
    'name': 'Sonja',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\sonja.png',
    'sig_img': 'images\\items\\sonja sigitem.png',
    'sig': 'The Lotus Blade',
    'skills': {
        'skill_1': 'Wind\'s Edge',
        'skill_2': 'Maelstrom',
        'skill_3': 'Dueling Blades',
        'skill_4': 'Winds of Fury',
        'skill_5': 'Maelstrom'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Steixius' : {
    'name': 'Steixius',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Debuffer',
    'img': 'images\\heroes\\steixius.png',
    'sig_img': 'images\\items\\steixius sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Fouled Cleave',
        'skill_2': 'Fetid Stench',
        'skill_3': '',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#026B5C',
    'rarity': 'Common',
    },
    'Talene' : {
    'name': 'Talene',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\talene.png',
    'sig_img': 'images\\items\\talene sigitem.png',
    'sig': 'Heart Of The Phoenix',
    'skills': {
        'skill_1': 'Fire Born',
        'skill_2': 'Meteor Shower',
        'skill_3': 'Phoenix Rising',
        'skill_4': 'Afterglow',
        'skill_5': 'Resurgence'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Tarnos' : {
    'name': 'Tarnos',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\tarnos.png',
    'sig_img': 'images\\items\\tarnos sigitem.png',
    'sig': 'Avenger\'s Blade',
    'skills': {
        'skill_1': 'Atoner\'s Prison',
        'skill_2': 'Oathbearer\'s Strike',
        'skill_3': 'Divine Punishment',
        'skill_4': 'Pillars of Sin',
        'skill_5': 'Avenger\'s Blade'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Tasi' : {
    'name': 'Tasi',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Control',
    'img': 'images\\heroes\\tasi.png',
    'sig_img': 'images\\items\\tasi sigitem.png',
    'sig': 'The Dream Halo',
    'skills': {
        'skill_1': 'SLUMBER',
        'skill_2': 'DREAM SPIRIT',
        'skill_3': 'BANISHMENT',
        'skill_4': 'TELEPORTATION',
        'skill_5': 'Diminish'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Thali' : {
    'name': 'Thali',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\thali.png',
    'sig_img': 'images\\items\\thali sigitem.png',
    'sig': 'Red Almandine',
    'skills': {
        'skill_1': 'Pyromaniac',
        'skill_2': 'Fire Rapture',
        'skill_3': 'Flame Burst',
        'skill_4': 'Pyromancy',
        'skill_5': 'Fiery Focus'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Thane' : {
    'name': 'Thane',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\thane.png',
    'sig_img': 'images\\items\\thane sigitem.png',
    'sig': 'The Lotus Blade',
    'skills': {
        'skill_1': 'Eviscerate',
        'skill_2': 'Lunge',
        'skill_3': 'Execution',
        'skill_4': 'Focus',
        'skill_5': 'Focused Finesse'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Theowyn' : {
    'name': 'Theowyn',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\theowyn.png',
    'sig_img': 'images\\items\\theowyn sigitem.png',
    'sig': 'Crown Of Thorns',
    'skills': {
        'skill_1': 'Spectral Divergence',
        'skill_2': 'Haunting Specter',
        'skill_3': 'Spectral Curse',
        'skill_4': 'Song of Mourning',
        'skill_5': 'Sorrowful Affliction'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Thesku' : {
    'name': 'Thesku',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Control',
    'img': 'images\\heroes\\thesku.png',
    'sig_img': 'images\\items\\thesku sigitem.png',
    'sig': 'Bone Flute',
    'skills': {
        'skill_1': 'Ancient Terror',
        'skill_2': 'Neurotoxicity',
        'skill_3': 'Serpents Mark',
        'skill_4': 'Cursed Flame',
        'skill_5': 'Serpents Guard'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Thoran' : {
    'name': 'Thoran',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Tank',
    'img': 'images\\heroes\\thoran.png',
    'sig_img': 'images\\items\\thoran sigitem.png',
    'sig': 'The Vengeful Crown',
    'skills': {
        'skill_1': 'Retaliation',
        'skill_2': 'Domination',
        'skill_3': 'Resurrection',
        'skill_4': 'Taint',
        'skill_5': 'Kings Will'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Tidus' : {
    'name': 'Tidus',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\tidus.png',
    'sig_img': 'images\\items\\tidus sigitem.png',
    'sig': 'Hatred\'S Bite',
    'skills': {
        'skill_1': 'Twisted Fate',
        'skill_2': 'Frenzied Strikes',
        'skill_3': 'Battle Howl',
        'skill_4': 'Savagery',
        'skill_5': 'Hatred\'s Bite'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Titus' : {
    'name': 'Titus',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Tank',
    'img': 'images\\heroes\\titus.png',
    'sig_img': 'images\\items\\titus sigitem.png',
    'sig': 'Mountain Star',
    'skills': {
        'skill_1': 'Temple Guardian',
        'skill_2': 'Energy Absorption',
        'skill_3': 'Spiral',
        'skill_4': 'Guardians Shield',
        'skill_5': 'Final Aegis'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Torne' : {
    'name': 'Torne',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Tank',
    'img': 'images\\heroes\\torne.png',
    'sig_img': 'images\\items\\torne sigitem.png',
    'sig': 'WandererS Plight',
    'skills': {
        'skill_1': 'Piercing Bones',
        'skill_2': 'Bone Prison',
        'skill_3': 'Seething Death',
        'skill_4': 'Absorption',
        'skill_5': 'Baneful Focus'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Treznor' : {
    'name': 'Treznor',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Control',
    'img': 'images\\heroes\\treznor.png',
    'sig_img': 'images\\items\\treznor sigitem.png',
    'sig': 'Blade Of Promise',
    'skills': {
        'skill_1': 'Purging Cleave',
        'skill_2': 'Death Charge',
        'skill_3': 'Spear of Valor',
        'skill_4': 'Soul Barricade',
        'skill_5': 'Oath of Faith'
    },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Ukyo' : {
    'name': 'Ukyo',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\ukyo.png',
    'sig_img': 'images\\items\\ukyo sigitem.png',
    'sig': 'Nameless Self-Made Sword',
    'skills': {
        'skill_1': 'Hientorajin',
        'skill_2': 'Snowfall Slash',
        'skill_3': 'Phantom Strike',
        'skill_4': 'Swallow Swipe',
        'skill_5': 'Rage Eruption'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Ulmus' : {
    'name': 'Ulmus',
    'fac': 'Wilder',
    'fac_img': 'images\\factions\\wilder.png',
    'role': 'Tank',
    'img': 'images\\heroes\\ulmus.png',
    'sig_img': 'images\\items\\ulmus sigitem.png',
    'sig': 'Totem Scoring',
    'skills': {
        'skill_1': 'Deep Roots',
        'skill_2': 'Writhing Roots',
        'skill_3': 'Forests Oath',
        'skill_4': 'Life Torrent',
        'skill_5': 'Healing Roots'
    },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Ulric' : {
    'name': 'Ulric',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\ulric.png',
    'sig_img': 'images\\items\\ulric sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Knockback',
        'skill_2': 'Guard',
        'skill_3': '',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#FFFFFF',
    'rarity': 'Common',
    },
    'Vedan' : {
    'name': 'Vedan',
    'fac': 'Graveborn',
    'fac_img': 'images\\factions\\graveborn.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\vedan.png',
    'sig_img': 'images\\items\\vedan sigitem.png',
    'sig': '',
    'skills': {
        'skill_1': 'Dark Swarm',
        'skill_2': 'Vitality',
        'skill_3': 'Thirst',
        'skill_4': '',
        'skill_5': ''
    },
    'background': '#026B5C',
    'rarity': 'Legendary',
    },
    'Veithael' : {
    'name': 'Veithael',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Tank',
    'img': 'images\\heroes\\veithael.png',
    'sig_img': 'images\\items\\veithael sigitem.png',
    'sig': 'Resplendence',
    'skills': {
        'skill_1': 'Warmonger',
        'skill_2': 'Brutal Backswing',
        'skill_3': 'Hear No Evil',
        'skill_4': 'Head Held High',
        'skill_5': 'Godly Physique'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Vurk' : {
    'name': 'Vurk',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Aoe',
    'img': 'images\\heroes\\vurk.png',
    'sig_img': 'images\\items\\vurk sigitem.png',
    'sig': 'Shadow Stinger',
    'skills': {
        'skill_1': 'Mania',
        'skill_2': 'Piercing Bolt',
        'skill_3': 'Poison Vial',
        'skill_4': 'Poison Traps',
        'skill_5': 'Madness'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Vyloris' : {
    'name': 'Vyloris',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Burst Damage',
    'img': 'images\\heroes\\vyloris.png',
    'sig_img': 'images\\items\\vyloris sigitem.png',
    'sig': 'Annulus of Lethality',
    'skills': {
        'skill_1': 'Cruel Endeavors',
        'skill_2': 'Cursed Agony',
        'skill_3': 'Fatal Embrace',
        'skill_4': 'Everlasting Torment',
        'skill_5': 'Havoc'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Walker' : {
    'name': 'Walker',
    'fac': 'Lightbearer',
    'fac_img': 'images\\factions\\lightbearer.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\walker.png',
    'sig_img': 'images\\items\\walker sigitem.png',
    'sig': 'Ragin Bull',
    'skills': {
        'skill_1': 'Saloon Blast',
        'skill_2': 'Spittoon Smack',
        'skill_3': 'Gunslinger',
        'skill_4': 'Old Faithful',
        'skill_5': 'Hotshot'
    },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Warek' : {
    'name': 'Warek',
    'fac': 'Mauler',
    'fac_img': 'images\\factions\\mauler.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\warek.png',
    'sig_img': 'images\\items\\warek sigitem.png',
    'sig': 'Coward Crusher',
    'skills': {
        'skill_1': 'Bloodlust',
        'skill_2': 'Bonebreaker',
        'skill_3': 'Extricate',
        'skill_4': 'Carnal Rage',
        'skill_5': 'Brawlers Resistance'
    },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Wu Kong' : {
    'name': 'Wu Kong',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\wu kong.png',
    'sig_img': 'images\\items\\wu kong sigitem.png',
    'sig': 'The Golden Rod',
    'skills': {
        'skill_1': 'Cloud Clones',
        'skill_2': 'Bludgeon',
        'skill_3': 'Falling Fury',
        'skill_4': 'Foresight',
        'skill_5': 'Golden Barrier'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Yennefer' : {
    'name': 'Yennefer',
    'fac': 'Dimensional',
    'fac_img': 'images\\factions\\dimensional.png',
    'role': 'Buffer',
    'img': 'images\\heroes\\yennefer.png',
    'sig_img': 'images\\items\\yennefer sigitem.png',
    'sig': 'Yennefer\'s Necklace',
    'skills': {
        'skill_1': 'Frontline Tatics',
        'skill_2': 'Lilac & Gooseberries',
        'skill_3': 'Sorceress\' Wrath',
        'skill_4': 'Magic Barrier',
        'skill_5': 'Aligned Defense'
    },
    'background': '#1F75FE',
    'rarity': 'Ascended',
    },
    'Zaphrael' : {
    'name': 'Zaphrael',
    'fac': 'Celestial',
    'fac_img': 'images\\factions\\celestial.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\zaphrael.png',
    'sig_img': 'images\\items\\zaphrael sigitem.png',
    'sig': 'Arc Of Justice',
    'skills': {
        'skill_1': 'Lightning Purge',
        'skill_2': 'Thunderstorm',
        'skill_3': 'Lightning Arc',
        'skill_4': 'Static Charge',
        'skill_5': 'Zeal'
    },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Zikis' : {
    'name': 'Zikis',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Continuous Damage',
    'img': 'images\\heroes\\zikis.png',
    'sig_img': 'images\\items\\zikis sigitem.png',
    'sig': 'Wings Of Lethargy',
    'skills': {
        'skill_1': 'Burning Sight',
        'skill_2': 'Corrosive Indolence',
        'skill_3': 'Languid Eye',
        'skill_4': 'Hatred',
        'skill_5': 'Bewilderment'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Zolrath' : {
    'name': 'Zolrath',
    'fac': 'Hypogean',
    'fac_img': 'images\\factions\\hypogean.png',
    'role': 'Assassin',
    'img': 'images\\heroes\\zolrath.png',
    'sig_img': 'images\\items\\zolrath sigitem.png',
    'sig': 'Hourglass Of Time',
    'skills': {
        'skill_1': 'Time Rift',
        'skill_2': 'Doppelganger',
        'skill_3': 'Annihilate',
        'skill_4': 'Déjà vu',
        'skill_5': 'Prey'
    },
    'background': '#712F85',
    'rarity': 'Ascended',
    }
}
