# CREATE A DICIONARY WITH THE DATA FROM THE MAIN FILE RELATED TO THE HEROES
heroes_dict = {
    'Ainz Ooal Gown' : {
        'name': 'Ainz Ooal Gown',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Ainz Ooal Gown.png',
        'sig_img': 'images\\items\\Ainz Ooal Gown sigitem.png',
        'sig': 'Staff Of Ainz Ooal Gown',
        'skills': {
            'skill_1': ' Fallen Down',
            'skill_2': ' Magic Caster',
            'skill_3': ' The Goal of All Life Is Death',
            'skill_4': ' Steady Preparations',
            'skill_5': 'Cash Items'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Alaro' : {
        'name': 'Alaro',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Alaro.png',
        'sig_img': 'images\\items\\Alaro sigitem.png',
        'sig': 'MaulerS Horn',
        'skills': {
            'skill_1': ' Unwanted Surprises',
            'skill_2': ' Incognito Mode',
            'skill_3': ' Dummy Double',
            'skill_4': ' Snooping Ambush',
            'skill_5': 'All Too Easy'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Albedo' : {
        'name': 'Albedo',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Albedo.png',
        'sig_img': 'images\\items\\Albedo sigitem.png',
        'sig': 'Ginnungagap',
        'skills': {
            'skill_1': 'Ginnungagap',
            'skill_2': ' Black Guard',
            'skill_3': ' Shield Lord',
            'skill_4': ' Hermes Trismegistus',
            'skill_5': 'Guardian Overseer'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Alna' : {
        'name': 'Alna',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\alna.png',
        'sig_img': 'AFK Compendium/images\\items\\Alna sigitem.png',
        'sig': 'Frostbite',
        'skills': {
            'skill_1': 'Winter War Cry',
            'skill_2': 'Freezing Pierce',
            'skill_3': 'Winter\'s Call',
            'skill_4': 'Frozen Fury',
            'skill_5': 'Unrelenting Heart'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Angelo' : {
        'name': 'Angelo',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Angelo.png',
        'sig_img': 'images\\items\\Angelo sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': ' Love and Peace',
            'skill_2': ' Encourage',
            'skill_3': ' Restoration',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FFFFFF',
        'rarity': 'Legendary',
    },
    'Ankhira' : {
        'name': 'Ankhira',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\Ankhira.png',
        'sig_img': 'images\\items\\Ankhira sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': ' Venomous Bile',
            'skill_2': ' Corrosion',
            'skill_3': ' Coccoon',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FF0000',
        'rarity': 'Legendary',
    },
    'Anoki' : {
        'name': 'Anoki',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Control',
        'img': 'images\\heroes\\Anoki.png',
        'sig_img': 'images\\items\\Anoki sigitem.png',
        'sig': 'Blood Guards Warhorn',
        'skills': {
            'skill_1': ' Savage Stampede',
            'skill_2': ' Raging Stomp',
            'skill_3': ' Born To Lead',
            'skill_4': ' Horn of War',
            'skill_5': 'War Fury'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Antandra' : {
        'name': 'Antandra',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Antandra.png',
        'sig_img': 'images\\items\\Antandra sigitem.png',
        'sig': 'Dances-In-Blood',
        'skills': {
            'skill_1': 'Fury Strike',
            'skill_2': 'Mark of the Wild',
            'skill_3': 'Piercing Assault',
            'skill_4': 'Knockdown',
            'skill_5': 'Unconquerable'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Arden' : {
        'name': 'Arden',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Arden.png',
        'sig_img': 'images\\items\\Arden sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Force of Nature',
            'skill_2': 'Entangling Roots',
            'skill_3': 'Shield of Thorns',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#779A71',
        'rarity': 'Legendary',
    },
    'Arkadios' : {
        'name': 'Arkadios',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\Arkadios.png',
        'sig_img': 'images\\items\\Arkadios sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Gloomy Cloud',
            'skill_2': 'Hunters Glare',
            'skill_3': '',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FF0000',
        'rarity': 'Common',
    },
    'Arthur' : {
        'name': 'Arthur',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Arthur.png',
        'sig_img': 'images\\items\\Arthur sigitem.png',
        'sig': 'Excalibur',
        'skills': {
            'skill_1': 'Smite',
            'skill_2': 'Excaliburs Fury',
            'skill_3': 'Kings Blessing',
            'skill_4': 'Shield of Honor',
            'skill_5': 'Battle Rally'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Astar' : {
        'name': 'Astar',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Regen',
        'img': 'images\\heroes\\Astar.png',
        'sig_img': 'images\\items\\Astar sigitem.png',
        'sig': 'Excalibur',
        'skills': {
            'skill_1': 'Life Sparks',
            'skill_2': 'Lanterns Flame',
            'skill_3': 'Flame Seeds',
            'skill_4': 'Aura of Fire',
            'skill_5': 'Burning Wave'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Athalia' : {
        'name': 'Athalia',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Athalia.png',
        'sig_img': 'images\\items\\Athalia sigitem.png',
        'sig': 'The Sin Purgers',
        'skills': {
            'skill_1': 'Divine Fury',
            'skill_2': 'Judgement',
            'skill_3': 'Purging Frenzy',
            'skill_4': 'Protection',
            'skill_5': 'Bloodless'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Audrae' : {
        'name': 'Audrae',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Audrae.png',
        'sig_img': 'images\\items\\Audrae sigitem.png',
        'sig': 'Stellar Bow And Arrow',
        'skills': {
            'skill_1': 'Cosmic Shower',
            'skill_2': 'Cosmic Assault',
            'skill_3': 'Cores Protection',
            'skill_4': 'Focus Fire',
            'skill_5': 'Astral Enclosure'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Baden' : {
        'name': 'Baden',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Baden.png',
        'sig_img': 'images\\items\\Baden sigitem.png',
        'sig': 'Spear Of Decay',
        'skills': {
            'skill_1': 'Phantom Assassin',
            'skill_2': 'Phantom Strike',
            'skill_3': 'Spectral Onslaught',
            'skill_4': 'Spectral Surge',
            'skill_5': 'Phantom Force'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Belinda' : {
        'name': 'Belinda',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Belinda.png',
        'sig_img': 'images\\items\\Belinda sigitem.png',
        'sig': 'Staff Of Light',
        'skills': {
            'skill_1': 'Divine Light',
            'skill_2': 'Divine Retribution',
            'skill_3': 'Brilliance',
            'skill_4': 'Blessing',
            'skill_5': 'Gift of Heaven'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Bloodsnarl' : {
        'name': 'Bloodsnarl',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Bloodsnarl.png',
        'sig_img': 'images\\items\\Bloodsnarl sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Raging Spiral',
            'skill_2': 'Hurl',
            'skill_3': '',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FF0000',
        'rarity': 'Common',
    },
    'Brutus' : {
        'name': 'Brutus',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Brutus.png',
        'sig_img': 'images\\items\\Brutus sigitem.png',
        'sig': 'Rends-The-Weak',
        'skills': {
            'skill_1': 'Whirlwind',
            'skill_2': 'Roar',
            'skill_3': 'Brutal Defiance',
            'skill_4': 'Last Gasp',
            'skill_5': 'Upsurge'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Cecilia' : {
        'name': 'Cecilia',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Cecilia.png',
        'sig_img': 'images\\items\\Cecilia sigitem.png',
        'sig': 'Sacred Book Of Cleansing',
        'skills': {
            'skill_1': 'Judgement Day',
            'skill_2': 'Blade of Purification',
            'skill_3': 'Atonement',
            'skill_4': 'Devil Trap',
            'skill_5': 'Repentance'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Daimon' : {
        'name': 'Daimon',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Daimon.png',
        'sig_img': 'images\\items\\Daimon sigitem.png',
        'sig': 'Stitchy',
        'skills': {
            'skill_1': 'Soul Feast',
            'skill_2': 'Blood Shield',
            'skill_3': 'Inanimate Companion',
            'skill_4': 'Forbidden Power',
            'skill_5': 'Soul Sunder'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Desira' : {
        'name': 'Desira',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Regen',
        'img': 'images\\heroes\\Desira.png',
        'sig_img': 'images\\items\\Desira sigitem.png',
        'sig': 'Shell Of Treason',
        'skills': {
            'skill_1': 'Sirens Call',
            'skill_2': 'Hatreds Mark',
            'skill_3': 'Oceanic Shield',
            'skill_4': 'Oceanic Mist',
            'skill_5': 'Concealing Mist'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Dreaf' : {
        'name': 'Dreaf',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\Dreaf.png',
        'sig_img': 'images\\items\\Dreaf sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Noxious Seeds',
    "        'skill_2': 'Piercing Spines	',"
            'skill_3': '',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#779A71',
        'rarity': 'Common',
    },
    'Drez' : {
        'name': 'Drez',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Drez.png',
        'sig_img': 'images\\items\\Drez sigitem.png',
        'sig': 'Ivory Piercer',
        'skills': {
            'skill_1': 'Deadly Ambush',
            'skill_2': 'Bloody Evisceration',
            'skill_3': 'Tactical Retreat',
            'skill_4': 'Rabid Slice',
            'skill_5': 'Hunters Shield'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Eironn' : {
        'name': 'Eironn',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Eironn.png',
        'sig_img': 'images\\items\\Eironn sigitem.png',
        'sig': 'Elemental Blades',
        'skills': {
            'skill_1': 'Elemental Surge',
            'skill_2': 'Twin Force',
            'skill_3': 'Vortex',
            'skill_4': 'Sylvan Oath',
            'skill_5': 'Chill'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Eletha' : {
        'name': 'Eletha',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Eletha.png',
        'sig_img': 'images\\items\\Eletha sigitem.png',
        'sig': '',
        'skills': {
    "        'skill_1': 'Piercing Blow	',"
    "        'skill_2': 'Bloody Frenzy	',"
            'skill_3': '',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#779A71',
        'rarity': 'Common',
    },
    'Elijah & Lailah' : {
        'name': 'Elijah & Lailah',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Elijah & Lailah.png',
        'sig_img': 'images\\items\\Elijah & Lailah sigitem.png',
        'sig': 'Bonding Feathers',
        'skills': {
            'skill_1': 'Hope',
            'skill_2': 'Grace',
            'skill_3': 'Cleanse',
            'skill_4': 'Unity',
            'skill_5': 'Blessed Binding'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Eluard' : {
        'name': 'Eluard',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Eluard.png',
        'sig_img': 'images\\items\\Eluard sigitem.png',
        'sig': 'Golden Visage',
        'skills': {
            'skill_1': 'Sanctimony',
            'skill_2': 'Divine Miracle',
            'skill_3': 'Prayer of Protection',
            'skill_4': 'Judgment',
            'skill_5': 'Judgement'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Estrilda' : {
        'name': 'Estrilda',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Estrilda.png',
        'sig_img': 'images\\items\\Estrilda sigitem.png',
        'sig': 'Banner Of Rayne',
        'skills': {
            'skill_1': 'Joust',
            'skill_2': 'Royal Charge',
            'skill_3': 'Inspire',
            'skill_4': 'Ridicule',
            'skill_5': 'In Command'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Ezio' : {
        'name': 'Ezio',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Ezio.png',
        'sig_img': 'images\\items\\Ezio sigitem.png',
        'sig': 'Hidden Blade',
        'skills': {
            'skill_1': 'Eagle Vision',
            'skill_2': 'Final Retribution',
            'skill_3': 'Smoke Bomb',
            'skill_4': 'Evasion',
            'skill_5': 'Assassins Target'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Ezizh' : {
        'name': 'Ezizh',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\Ezizh.png',
        'sig_img': 'images\\items\\Ezizh sigitem.png',
        'sig': 'Armor Of Ruin',
        'skills': {
            'skill_1': 'Fissure',
            'skill_2': 'Feeble Mind',
            'skill_3': 'Horrify',
            'skill_4': 'Mental Fury',
            'skill_5': 'Immolate'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Fane' : {
        'name': 'Fane',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\Fane.png',
        'sig_img': 'images\\items\\Fane sigitem.png',
        'sig': 'Bone Hook',
        'skills': {
            'skill_1': 'Malign Judgement',
            'skill_2': 'Prisoner of Despair',
            'skill_3': 'Soul Impaler',
            'skill_4': 'Unscrupulous Jailer',
            'skill_5': 'Prison Master'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Fawkes' : {
        'name': 'Fawkes',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Control',
        'img': 'images\\heroes\\Fawkes.png',
        'sig_img': 'images\\items\\Fawkes sigitem.png',
        'sig': 'The Soul Prision',
        'skills': {
            'skill_1': 'Purification',
            'skill_2': 'Abate',
            'skill_3': 'Confine',
            'skill_4': 'Silver Bolt',
            'skill_5': 'Purged Perseverance'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Ferael' : {
        'name': 'Ferael',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Ferael.png',
        'sig_img': 'images\\items\\Ferael sigitem.png',
        'sig': 'HaunterS Hand',
        'skills': {
            'skill_1': 'Nether Blaze',
            'skill_2': 'Accursed Arrow',
            'skill_3': 'Terrorize',
            'skill_4': 'Corrupted Spirit',
            'skill_5': 'Anguished Spirit'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Flora' : {
        'name': 'Flora',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Flora.png',
        'sig_img': 'images\\items\\Flora sigitem.png',
        'sig': 'The Serene Branch',
        'skills': {
            'skill_1': 'Sea of Flowers',
            'skill_2': 'Airborne',
            'skill_3': 'Swoop',
            'skill_4': 'Rejuvenation',
            'skill_5': 'Diminish'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Framton' : {
        'name': 'Framton',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Framton.png',
        'sig_img': 'images\\items\\Framton sigitem.png',
        'sig': 'Blaze Vambraces',
        'skills': {
            'skill_1': 'Blazing Meteor',
            'skill_2': 'Burning Vengeance',
            'skill_3': 'Fists of Fire',
            'skill_4': 'Flaming Feast',
            'skill_5': 'Eternal Flame'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Golus' : {
        'name': 'Golus',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Control',
        'img': 'images\\heroes\\Golus.png',
        'sig_img': 'images\\items\\Golus sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Collision',
            'skill_2': 'Outburst',
            'skill_3': 'Unwavering Will',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FF0000',
        'rarity': 'Legendary',
    },
    'Gorvo' : {
        'name': 'Gorvo',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Gorvo.png',
        'sig_img': 'images\\items\\Gorvo sigitem.png',
        'sig': 'Gate Crasher',
        'skills': {
            'skill_1': 'Battle Cry',
            'skill_2': 'Dive Bomb',
            'skill_3': 'Shell Shock',
            'skill_4': 'Shell Shield',
            'skill_5': 'Nature’s Shield'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Granit' : {
        'name': 'Granit',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Granit.png',
        'sig_img': 'images\\items\\Granit sigitem.png',
        'sig': 'DesertS Core',
        'skills': {
            'skill_1': 'Sand Vortex',
            'skill_2': 'Earth Tremors',
            'skill_3': 'Stone Skin',
            'skill_4': 'Earthen Resilience',
            'skill_5': 'Earthly Rejuvenation'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Grezhul' : {
        'name': 'Grezhul',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Grezhul.png',
        'sig_img': 'images\\items\\Grezhul sigitem.png',
        'sig': 'The Slayer Blades',
        'skills': {
            'skill_1': 'Reanimate',
            'skill_2': 'Demonic Assault',
            'skill_3': 'Shadow Shield',
            'skill_4': 'Deathly Protection',
            'skill_5': 'Reanimation'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Gwyneth' : {
        'name': 'Gwyneth',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Gwyneth.png',
        'sig_img': 'images\\items\\Gwyneth sigitem.png',
        'sig': 'Shooting Star',
        'skills': {
            'skill_1': 'Divine Arrow',
            'skill_2': 'Flaming Arrows',
            'skill_3': 'Lightning Arrows',
            'skill_4': 'Strength In Numbers',
            'skill_5': 'Focus Fire'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Haelus' : {
        'name': 'Haelus',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Haelus.png',
        'sig_img': 'images\\items\\Haelus sigitem.png',
        'sig': 'The Peerless Obelisk',
        'skills': {
            'skill_1': 'Laws of Creation',
            'skill_2': 'Divine Projection',
            'skill_3': 'Sphere of Craftsmanship',
            'skill_4': 'Born Blessings',
            'skill_5': 'Concealing Force'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Hendrik' : {
        'name': 'Hendrik',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Hendrik.png',
        'sig_img': 'images\\items\\Hendrik sigitem.png',
        'sig': 'The Bastion',
        'skills': {
            'skill_1': 'Crippling Blow',
            'skill_2': 'Shield Bash',
            'skill_3': 'Sacrificial Shield',
            'skill_4': 'Standfast',
            'skill_5': 'Steadfast'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Hodgkin' : {
        'name': 'Hodgkin',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Hodgkin.png',
        'sig_img': 'images\\items\\Hodgkin sigitem.png',
        'sig': 'Soul Devourers',
        'skills': {
            'skill_1': 'The Immortal',
            'skill_2': 'Soul Devourer',
            'skill_3': 'Jolly Roger',
            'skill_4': 'Revilers Defiance',
            'skill_5': 'Pirates Greed'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Hogan' : {
        'name': 'Hogan',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Control',
        'img': 'images\\heroes\\Hogan.png',
        'sig_img': 'images\\items\\Hogan sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Knights Fury',
            'skill_2': 'Zealous Strike',
            'skill_3': 'Unwavering Will',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FFFFFF',
        'rarity': 'Legendary',
    },
    'Ira' : {
        'name': 'Ira',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\Ira.png',
        'sig_img': 'images\\items\\Ira sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Hail of Arrows',
            'skill_2': 'Glacial Arrow',
            'skill_3': 'Piercing Arrow',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#779A71',
        'rarity': 'Legendary',
    },
    'Isabella' : {
        'name': 'Isabella',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Isabella.png',
        'sig_img': 'images\\items\\Isabella sigitem.png',
        'sig': 'Tome Of The Dead',
        'skills': {
            'skill_1': 'Decimation',
            'skill_2': 'Void Barrage',
            'skill_3': 'Psi Reap',
            'skill_4': 'Surge',
            'skill_5': 'Lightning Barrage'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Izold' : {
        'name': 'Izold',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Izold.png',
        'sig_img': 'images\\items\\Izold sigitem.png',
        'sig': 'Doomstriker Syringe',
        'skills': {
            'skill_1': 'Toxic Transfusion',
            'skill_2': 'Noxious Blast',
            'skill_3': 'Needle Strike',
            'skill_4': 'Hypodermic Healing',
            'skill_5': 'Lethal Dose'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Joker' : {
        'name': 'Joker',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Joker.png',
        'sig_img': 'images\\items\\Joker sigitem.png',
        'sig': 'Vile Sword',
        'skills': {
            'skill_1': 'Maeigaon',
            'skill_2': 'Adverse Reaction',
            'skill_3': 'Concentrated Fire',
            'skill_4': 'All-Out Attack',
            'skill_5': 'Widespread Attack'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Kaz' : {
        'name': 'Kaz',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Kaz.png',
        'sig_img': 'images\\items\\Kaz sigitem.png',
        'sig': 'The NightS Kiss',
        'skills': {
            'skill_1': 'Assassinate',
            'skill_2': 'Triple Strike',
            'skill_3': 'Evasive Strike',
            'skill_4': 'Feline Finesse',
            'skill_5': 'Elude'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Kelthur' : {
        'name': 'Kelthur',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Kelthur.png',
        'sig_img': 'images\\items\\Kelthur sigitem.png',
        'sig': 'The Harvester',
        'skills': {
            'skill_1': 'Blades of Fury',
            'skill_2': 'Retaliation',
            'skill_3': 'Displace',
            'skill_4': 'Ethereal Resurgence',
            'skill_5': 'Blood Sap'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Khasos' : {
        'name': 'Khasos',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Khasos.png',
        'sig_img': 'images\\items\\Khasos sigitem.png',
        'sig': 'Chief Choppers',
        'skills': {
            'skill_1': 'Spinning Obliteration',
            'skill_2': 'Concentration',
            'skill_3': 'Throwing Axe',
            'skill_4': 'Rabid Thirst',
            'skill_5': 'Precision'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Khazard' : {
        'name': 'Khazard',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Control',
        'img': 'images\\heroes\\Khazard.png',
        'sig_img': 'images\\items\\Khazard sigitem.png',
        'sig': 'The Frigid Aura',
        'skills': {
            'skill_1': 'Frozen Mist',
            'skill_2': 'Glacial Shards',
            'skill_3': 'Frozen Beam',
            'skill_4': 'Frost Serpent',
            'skill_5': 'Frozen Curse'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Kren' : {
        'name': 'Kren',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Kren.png',
        'sig_img': 'images\\items\\Kren sigitem.png',
        'sig': '“Hot Stuff” & “Lady”',
        'skills': {
            'skill_1': 'Bomb Voyage',
            'skill_2': 'Enshrouding Bomb',
            'skill_3': 'Old Pal',
            'skill_4': 'Concussive Blast',
            'skill_5': 'Potent Firepower'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Leofric' : {
        'name': 'Leofric',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\Leofric.png',
        'sig_img': 'images\\items\\Leofric sigitem.png',
        'sig': 'Shadow Mastiff Cane',
        'skills': {
            'skill_1': 'Shadow Mastiff',
            'skill_2': 'Hell Wyrms',
            'skill_3': 'Unmasked Horror',
            'skill_4': 'Perfect Disguise',
            'skill_5': 'Heart of Malice'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Leonardo' : {
        'name': 'Leonardo',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Control',
        'img': 'images\\heroes\\Leonardo.png',
        'sig_img': 'images\\items\\Leonardo sigitem.png',
        'sig': 'The Creator',
        'skills': {
            'skill_1': 'Work of Art',
            'skill_2': 'Art Attack',
            'skill_3': 'Renaissance Cannon',
            'skill_4': 'Evacuation',
            'skill_5': 'The Machinist'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Lorsan' : {
        'name': 'Lorsan',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Lorsan.png',
        'sig_img': 'images\\items\\Lorsan sigitem.png',
        'sig': 'Wind Keeper',
        'skills': {
            'skill_1': 'Tempest',
            'skill_2': 'Inner Sight',
            'skill_3': 'Gale Force',
            'skill_4': 'Wind Ward',
            'skill_5': 'Fate'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Lucius' : {
        'name': 'Lucius',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Regen',
        'img': 'images\\heroes\\Lucius.png',
        'sig_img': 'images\\items\\Lucius sigitem.png',
        'sig': 'The Winged Protector',
        'skills': {
            'skill_1': 'Heavens Protection',
            'skill_2': 'Divine Strike',
            'skill_3': 'Divine Blessing',
            'skill_4': 'Blessed Shield',
            'skill_5': 'Divine Purge'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Lucretia' : {
        'name': 'Lucretia',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Lucretia.png',
        'sig_img': 'images\\items\\Lucretia sigitem.png',
        'sig': 'Dark Star',
        'skills': {
            'skill_1': 'Ungodly Defiance',
            'skill_2': 'Hellfire',
            'skill_3': 'Deathwish',
            'skill_4': 'Twin Terrors',
            'skill_5': 'Animus'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Lyca' : {
        'name': 'Lyca',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Lyca.png',
        'sig_img': 'images\\items\\Lyca sigitem.png',
        'sig': 'Starfall',
        'skills': {
            'skill_1': 'Star Shot',
            'skill_2': 'Rapid Arrows',
            'skill_3': 'Awe',
            'skill_4': 'Foes Fragility',
            'skill_5': 'Vision of Stars'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Mehira' : {
        'name': 'Mehira',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Control',
        'img': 'images\\heroes\\Mehira.png',
        'sig_img': 'images\\items\\Mehira sigitem.png',
        'sig': 'Lash Of Submission',
        'skills': {
            'skill_1': 'Mesmerize',
            'skill_2': 'Whiplash',
            'skill_3': 'Infatuation',
            'skill_4': 'Hellspawn',
            'skill_5': 'Carnal Bliss'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Melusina' : {
        'name': 'Melusina',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Melusina.png',
        'sig_img': 'images\\items\\Melusina sigitem.png',
        'sig': 'Staff Of Domination',
        'skills': {
            'skill_1': 'Dropping By',
            'skill_2': 'Treacherous Treehouse',
            'skill_3': 'Alchemic Witchcraft',
            'skill_4': 'Soul Pilfer',
            'skill_5': 'Soul Taker'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Merek' : {
        'name': 'Merek',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Merek.png',
        'sig_img': 'images\\items\\Merek sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Divine Blessing',
            'skill_2': 'Divine Vitality',
            'skill_3': '',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FFFFFF',
        'rarity': 'Common',
    },
    'Merlin' : {
        'name': 'Merlin',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Regen',
        'img': 'images\\heroes\\Merlin.png',
        'sig_img': 'images\\items\\Merlin sigitem.png',
        'sig': 'DestinyS Sight',
        'skills': {
            'skill_1': 'Destiny Foreseen',
            'skill_2': 'Magical Amelioration',
            'skill_3': 'Karmic Law',
            'skill_4': 'Guardian Owl',
            'skill_5': 'Shared Destiny'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Mezoth' : {
        'name': 'Mezoth',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Mezoth.png',
        'sig_img': 'images\\items\\Mezoth sigitem.png',
        'sig': 'Blood And Gore',
        'skills': {
            'skill_1': 'Devour',
            'skill_2': 'Abyssal Butchery',
            'skill_3': 'Demonic Hunger',
            'skill_4': 'Carnivorous Lust',
            'skill_5': 'Virulent Greed'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Mirael' : {
        'name': 'Mirael',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Mirael.png',
        'sig_img': 'images\\items\\Mirael sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Fire Phoenix',
            'skill_2': 'Fireball',
    "        'skill_3': 'Flame Shield	',"
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FFFFFF',
        'rarity': 'Legendary',
    },
    'Mishka' : {
        'name': 'Mishka',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Control',
        'img': 'images\\heroes\\Mishka.png',
        'sig_img': 'images\\items\\Mishka sigitem.png',
        'sig': 'Bear Talons',
        'skills': {
            'skill_1': 'Werebear',
            'skill_2': 'Dire Wolves',
            'skill_3': 'Call of the Wild',
            'skill_4': 'Natural Rejuvenation',
            'skill_5': 'Natural Defense'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Morael' : {
        'name': 'Morael',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Morael.png',
        'sig_img': 'images\\items\\Morael sigitem.png',
        'sig': 'Heart Of Zohra',
        'skills': {
            'skill_1': 'Cosmic Field',
            'skill_2': 'Cosmic Motion',
            'skill_3': 'Cosmic Fusion',
            'skill_4': 'Celestial Blessing',
            'skill_5': 'Astral Fortune'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Morrow' : {
        'name': 'Morrow',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Control',
        'img': 'images\\heroes\\Morrow.png',
        'sig_img': 'images\\items\\Morrow sigitem.png',
        'sig': 'Abyssal Tome',
        'skills': {
            'skill_1': 'Eye of Evil',
            'skill_2': 'Binding Terror',
            'skill_3': 'Demonic Murmurs',
            'skill_4': 'Abyssal Retribution',
            'skill_5': 'Murder of Crows'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Mortas' : {
        'name': 'Mortas',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Regen',
        'img': 'images\\heroes\\Mortas.png',
        'sig_img': 'images\\items\\Mortas sigitem.png',
        'sig': 'Deception',
        'skills': {
            'skill_1': 'Empowerment',
            'skill_2': 'Greed',
            'skill_3': 'Blood Pact',
            'skill_4': 'Devilish Deal',
            'skill_5': 'Trickery'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Morvus' : {
        'name': 'Morvus',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\Morvus.png',
        'sig_img': 'images\\items\\Morvus sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Sharpshooter',
            'skill_2': 'Concussive Grenade',
            'skill_3': 'Lethal Focus',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FFFFFF',
        'rarity': 'Legendary',
    },
    'Nakoruru' : {
        'name': 'Nakoruru',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Nakoruru.png',
        'sig_img': 'images\\items\\Nakoruru sigitem.png',
        'sig': 'Chichi-Ushi',
        'skills': {
            'skill_1': 'Running Chest Jab',
            'skill_2': 'Kamui Rimuse',
            'skill_3': 'Shichikapu Etu',
            'skill_4': 'Kamui Mutsube',
            'skill_5': 'Heavy Slash'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Nara' : {
        'name': 'Nara',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Nara.png',
        'sig_img': 'images\\items\\Nara sigitem.png',
        'sig': 'Bloodshed',
        'skills': {
            'skill_1': 'Butchery',
            'skill_2': 'Dismember',
            'skill_3': 'Impale',
            'skill_4': 'Terrify',
            'skill_5': 'Looming Death'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Nemora' : {
        'name': 'Nemora',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Regen',
        'img': 'images\\heroes\\Nemora.png',
        'sig_img': 'images\\items\\Nemora sigitem.png',
        'sig': 'The Blossom Spear',
        'skills': {
            'skill_1': 'Wild Wonder',
            'skill_2': 'Beguile',
            'skill_3': 'Mother Nature',
            'skill_4': 'Life Force',
            'skill_5': 'Natures Touch'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Niru' : {
        'name': 'Niru',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Niru.png',
        'sig_img': 'images\\items\\Niru sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Death Call',
            'skill_2': 'Life Leech',
            'skill_3': 'Soul Reaper',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#026B5C',
        'rarity': 'Legendary',
    },
    'Numisu' : {
        'name': 'Numisu',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Regen',
        'img': 'images\\heroes\\Numisu.png',
        'sig_img': 'images\\items\\Numisu sigitem.png',
        'sig': 'Mask Of Visions',
        'skills': {
            'skill_1': 'Resonating Blast',
            'skill_2': 'Rejuvenating Totem',
            'skill_3': 'Offensive Totem',
            'skill_4': 'Fanaticism',
            'skill_5': 'Totem Master'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Oden' : {
        'name': 'Oden',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Oden.png',
        'sig_img': 'images\\items\\Oden sigitem.png',
        'sig': 'Void Gazer',
        'skills': {
            'skill_1': 'Soul Burn',
            'skill_2': 'Void Lightning',
            'skill_3': 'Eviction',
            'skill_4': 'Eye of Evil',
            'skill_5': 'Vengeful Fury'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Ogi' : {
        'name': 'Ogi',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Control',
        'img': 'images\\heroes\\Ogi.png',
        'sig_img': 'images\\items\\Ogi sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Resilience',
            'skill_2': 'Ground Fissure',
            'skill_3': 'Bombard',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#779A71',
        'rarity': 'Legendary',
    },
    'Oku' : {
        'name': 'Oku',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Oku.png',
        'sig_img': 'images\\items\\Oku sigitem.png',
        'sig': 'Chitinous Shield',
        'skills': {
            'skill_1': 'Trembling Mountain',
            'skill_2': 'Vengeful Grievance',
            'skill_3': 'Beetle Bash',
            'skill_4': 'Besieging Fist',
            'skill_5': 'Forests Restoration'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Orthros' : {
        'name': 'Orthros',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Orthros.png',
        'sig_img': 'images\\items\\Orthros sigitem.png',
        'sig': 'The Heavenly Vision',
        'skills': {
            'skill_1': 'Time Suspension',
            'skill_2': 'Time Trap',
            'skill_3': 'Inertia',
            'skill_4': 'Celestial Vigor',
            'skill_5': 'Time Warp'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Oscar' : {
        'name': 'Oscar',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Oscar.png',
        'sig_img': 'images\\items\\Oscar sigitem.png',
        'sig': 'Exquisite Table Knife',
        'skills': {
            'skill_1': 'Aura of Haste',
            'skill_2': 'Fine Cuts',
            'skill_3': 'Slice and Dice',
            'skill_4': 'Unfazed',
            'skill_5': 'Uninvited Guest'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Peggy' : {
        'name': 'Peggy',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Regen',
        'img': 'images\\heroes\\Peggy.png',
        'sig_img': 'images\\items\\Peggy sigitem.png',
        'sig': 'Gorgeous Conch',
        'skills': {
            'skill_1': 'Duty Bound',
            'skill_2': 'Royal Scroll',
            'skill_3': 'Royal Guards',
            'skill_4': 'Royal Marksmen',
            'skill_5': 'Battle Hardened'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Pippa' : {
        'name': 'Pippa',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Pippa.png',
        'sig_img': 'images\\items\\Pippa sigitem.png',
        'sig': 'Branch Of Verdure',
        'skills': {
            'skill_1': 'Pippas Imitation',
            'skill_2': 'Pippas Pandemonium',
            'skill_3': 'Transmogrification',
            'skill_4': 'Astral Shift',
            'skill_5': 'Pippa Power'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Prince of Persia' : {
        'name': 'Prince of Persia',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Prince of Persia.png',
        'sig_img': 'images\\items\\Prince of Persia sigitem.png',
        'sig': 'Dagger Of Time',
        'skills': {
            'skill_1': 'Sands of Time',
            'skill_2': 'Tempest of Agony',
            'skill_3': 'Wall Dive Attack',
            'skill_4': 'Concentrated Force',
            'skill_5': 'Bounding Agility'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Queen' : {
        'name': 'Queen',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Queen.png',
        'sig_img': 'images\\items\\Queen sigitem.png',
        'sig': 'Sanction',
        'skills': {
            'skill_1': 'Stationary Drifter',
            'skill_2': 'Freidyne',
            'skill_3': 'Attack & Defend',
            'skill_4': 'Ms. Post-Apocalyptic Raider',
            'skill_5': 'Edge of Death'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Raine' : {
        'name': 'Raine',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Raine.png',
        'sig_img': 'images\\items\\Raine sigitem.png',
        'sig': 'Dueling Blasters',
        'skills': {
            'skill_1': 'Cripple',
            'skill_2': 'Barrage',
            'skill_3': 'Lock On',
            'skill_4': 'Exploit',
            'skill_5': 'Helping Hand'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Raku' : {
        'name': 'Raku',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Raku.png',
        'sig_img': 'images\\items\\Raku sigitem.png',
        'sig': 'Elemental Slingshot',
        'skills': {
            'skill_1': 'Acorn Cannon',
            'skill_2': 'Entangling Shot',
            'skill_3': 'Peckish',
            'skill_4': 'Rakus Mark',
            'skill_5': 'Troublemaker'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Respen' : {
        'name': 'Respen',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Respen.png',
        'sig_img': 'images\\items\\Respen sigitem.png',
        'sig': 'Mark Of The Wild',
        'skills': {
            'skill_1': 'Wind Spiral',
            'skill_2': 'Feathered Fury',
            'skill_3': 'Winged Attack',
            'skill_4': 'Winged Protection',
            'skill_5': 'Kindred Spirits'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Rigby' : {
        'name': 'Rigby',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Rigby.png',
        'sig_img': 'images\\items\\Rigby sigitem.png',
        'sig': 'Oak Barrel',
        'skills': {
            'skill_1': 'Barrel Bomb',
            'skill_2': 'Fire Breath',
            'skill_3': 'Drunken Frenzy',
            'skill_4': 'Well Rested',
            'skill_5': 'Fiery Demise'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Rosaline' : {
        'name': 'Rosaline',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Rosaline.png',
        'sig_img': 'images\\items\\Rosaline sigitem.png',
        'sig': 'Servitude',
        'skills': {
            'skill_1': 'Motivation',
            'skill_2': 'Crazy Crockery',
            'skill_3': 'Afternoon Tea',
            'skill_4': 'Spring Cleaning',
            'skill_5': 'Servitude'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Rowan' : {
        'name': 'Rowan',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Rowan.png',
        'sig_img': 'images\\items\\Rowan sigitem.png',
        'sig': 'The Gold Chime',
        'skills': {
            'skill_1': 'Dazzle',
            'skill_2': 'Avian Assault',
            'skill_3': 'Healthy Supplies',
            'skill_4': 'Damage Control',
            'skill_5': 'Thirsty Work'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Safiya' : {
        'name': 'Safiya',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Safiya.png',
        'sig_img': 'images\\items\\Safiya sigitem.png',
        'sig': 'Supremacy',
        'skills': {
            'skill_1': 'Falling Sun',
            'skill_2': 'Scattered Bolt',
            'skill_3': 'Static Field',
            'skill_4': 'Spectral Disruption',
            'skill_5': 'Arcane Power'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Satrana' : {
        'name': 'Satrana',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Satrana.png',
        'sig_img': 'images\\items\\Satrana sigitem.png',
        'sig': 'Blazing Ember',
        'skills': {
            'skill_1': 'Firedance',
            'skill_2': 'Flutter Flame',
            'skill_3': 'Fireseeds',
            'skill_4': 'Overflow',
            'skill_5': 'Mark of the Fox'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Saurus' : {
        'name': 'Saurus',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Saurus.png',
        'sig_img': 'images\\items\\Saurus sigitem.png',
        'sig': 'Hope’S Edge',
        'skills': {
            'skill_1': 'Phase Form',
            'skill_2': 'War Strike',
            'skill_3': 'Burst Strikes',
            'skill_4': 'Tenacity',
            'skill_5': 'Warriors Valor'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Saveas' : {
        'name': 'Saveas',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Saveas.png',
        'sig_img': 'images\\items\\Saveas sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Burning Acrimony',
    "        'skill_2': 'Bloodied Spear	',"
            'skill_3': 'Sacrificial Sustenance',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FF0000',
        'rarity': 'Legendary',
    },
    'Scarlet' : {
        'name': 'Scarlet',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Scarlet.png',
        'sig_img': 'images\\items\\Scarlet sigitem.png',
        'sig': 'Arcane Stabilizer',
        'skills': {
            'skill_1': 'Dark Rage',
            'skill_2': 'Shaded Corruption',
            'skill_3': 'Arcane Absorption',
            'skill_4': 'Dark Aura',
            'skill_5': 'Lingering Power'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Seirus' : {
        'name': 'Seirus',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Seirus.png',
        'sig_img': 'images\\items\\Seirus sigitem.png',
        'sig': 'Tidemaker',
        'skills': {
            'skill_1': 'Abhorrent Torrent',
            'skill_2': 'Deluge',
            'skill_3': 'Oceans Blessing',
            'skill_4': 'Free Flow',
            'skill_5': 'Sea Lord'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Sezis' : {
        'name': 'Sezis',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Control',
        'img': 'images\\heroes\\Sezis.png',
        'sig_img': 'images\\items\\Sezis sigitem.png',
        'sig': '',
        'skills': {
    "        'skill_1': 'Grim Swipe	',"
    "        'skill_2': 'Swiping Swing	',"
            'skill_3': '',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#026B5C',
        'rarity': 'Common',
    },
    'Shemira' : {
        'name': 'Shemira',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Shemira.png',
        'sig_img': 'images\\items\\Shemira sigitem.png',
        'sig': 'The Spirit Orb',
        'skills': {
            'skill_1': 'Tortured Souls',
            'skill_2': 'Soul Siphon',
            'skill_3': 'Silence',
            'skill_4': 'Wrath',
            'skill_5': 'Twisted Torture'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Silas' : {
        'name': 'Silas',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Silas.png',
        'sig_img': 'images\\items\\Silas sigitem.png',
        'sig': 'Augmentation Blades',
        'skills': {
            'skill_1': 'Injected Fury',
            'skill_2': 'Stimulated Rage',
            'skill_3': 'Double Dosage',
            'skill_4': 'Healing Haze',
            'skill_5': 'Adrenaline Shot'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Silvina' : {
        'name': 'Silvina',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Burst Damage',
        'img': 'images\\heroes\\Silvina.png',
        'sig_img': 'images\\items\\Silvina sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Fatal Strike',
            'skill_2': 'Abyssal Shield',
            'skill_3': 'First Blood',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#026B5C',
        'rarity': 'Legendary',
    },
    'Skreg' : {
        'name': 'Skreg',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Skreg.png',
        'sig_img': 'images\\items\\Skreg sigitem.png',
        'sig': 'Long Fang',
        'skills': {
            'skill_1': 'Beast of Burden',
            'skill_2': 'Brute Force',
            'skill_3': 'Ironskin',
            'skill_4': 'Stampede',
            'skill_5': 'Beast Rider'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Skriath' : {
        'name': 'Skriath',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Skriath.png',
        'sig_img': 'images\\items\\Skriath sigitem.png',
        'sig': 'Wisdom Keeper',
        'skills': {
            'skill_1': 'Desert Vortex',
            'skill_2': 'Death from Above',
            'skill_3': 'Sandstorm',
            'skill_4': 'Critical Insight',
            'skill_5': 'Boulder Blast'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Solise' : {
        'name': 'Solise',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Control',
        'img': 'images\\heroes\\Solise.png',
        'sig_img': 'images\\items\\Solise sigitem.png',
        'sig': 'Floral Cloak Of Hope',
        'skills': {
            'skill_1': 'Blossom Fall',
            'skill_2': 'Floral Disruption',
            'skill_3': 'Floral Specter',
            'skill_4': 'Forests Blessing',
            'skill_5': 'Flower Power'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Steixius' : {
        'name': 'Steixius',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Debuffer',
        'img': 'images\\heroes\\Steixius.png',
        'sig_img': 'images\\items\\Steixius sigitem.png',
        'sig': '',
        'skills': {
    "        'skill_1': 'Fouled Cleave	',"
    "        'skill_2': 'Fetid Stench	',"
            'skill_3': '',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#026B5C',
        'rarity': 'Common',
    },
    'Talene' : {
        'name': 'Talene',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Talene.png',
        'sig_img': 'images\\items\\Talene sigitem.png',
        'sig': 'Heart Of The Phoenix',
        'skills': {
            'skill_1': 'Fire Born',
            'skill_2': 'Meteor Shower',
            'skill_3': 'Phoenix Rising',
            'skill_4': 'Afterglow',
            'skill_5': 'Resurgence'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Tasi' : {
        'name': 'Tasi',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Control',
        'img': 'images\\heroes\\Tasi.png',
        'sig_img': 'images\\items\\Tasi sigitem.png',
        'sig': 'The Dream Halo',
        'skills': {
            'skill_1': 'SLUMBER',
            'skill_2': 'DREAM SPIRIT',
            'skill_3': 'BANISHMENT',
            'skill_4': 'TELEPORTATION',
            'skill_5': 'Diminish'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Thali' : {
        'name': 'Thali',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Thali.png',
        'sig_img': 'images\\items\\Thali sigitem.png',
        'sig': 'Red Almandine',
        'skills': {
            'skill_1': 'Pyromaniac',
            'skill_2': 'Fire Rapture',
            'skill_3': 'Flame Burst',
            'skill_4': 'Pyromancy',
            'skill_5': 'Fiery Focus'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Thane' : {
        'name': 'Thane',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Thane.png',
        'sig_img': 'images\\items\\Thane sigitem.png',
        'sig': 'The Lotus Blade',
        'skills': {
            'skill_1': 'Eviscerate',
            'skill_2': 'Lunge',
            'skill_3': 'Execution',
            'skill_4': 'Focus',
            'skill_5': 'Focused Finesse'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Theowyn' : {
        'name': 'Theowyn',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Theowyn.png',
        'sig_img': 'images\\items\\Theowyn sigitem.png',
        'sig': 'Crown Of Thorns',
        'skills': {
            'skill_1': 'Spectral Divergence',
            'skill_2': 'Haunting Specter',
            'skill_3': 'Spectral Curse',
            'skill_4': 'Song of Mourning',
            'skill_5': 'Sorrowful Affliction'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Thesku' : {
        'name': 'Thesku',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Control',
        'img': 'images\\heroes\\Thesku.png',
        'sig_img': 'images\\items\\Thesku sigitem.png',
        'sig': 'Bone Flute',
        'skills': {
            'skill_1': 'Ancient Terror',
            'skill_2': 'Neurotoxicity',
            'skill_3': 'Serpents Mark',
            'skill_4': 'Cursed Flame',
            'skill_5': 'Serpents Guard'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Thoran' : {
        'name': 'Thoran',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Thoran.png',
        'sig_img': 'images\\items\\Thoran sigitem.png',
        'sig': 'The Vengeful Crown',
        'skills': {
            'skill_1': 'Retaliation',
            'skill_2': 'Domination',
            'skill_3': 'Resurrection',
            'skill_4': 'Taint',
            'skill_5': 'Kings Will'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Tidus' : {
        'name': 'Tidus',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Tidus.png',
        'sig_img': 'images\\items\\Tidus sigitem.png',
        'sig': 'Hatred’S Bite',
        'skills': {
            'skill_1': 'Twisted Fate',
            'skill_2': 'Frenzied Strikes',
            'skill_3': 'Battle Howl',
            'skill_4': 'Savagery',
            'skill_5': 'Hatred’s Bite'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Titus' : {
        'name': 'Titus',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Titus.png',
        'sig_img': 'images\\items\\Titus sigitem.png',
        'sig': 'Mountain Star',
        'skills': {
            'skill_1': 'Temple Guardian',
            'skill_2': 'Energy Absorption',
            'skill_3': 'Spiral',
            'skill_4': 'Guardians Shield',
            'skill_5': 'Final Aegis'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Torne' : {
        'name': 'Torne',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Torne.png',
        'sig_img': 'images\\items\\Torne sigitem.png',
        'sig': 'WandererS Plight',
        'skills': {
            'skill_1': 'Piercing Bones',
            'skill_2': 'Bone Prison',
            'skill_3': 'Seething Death',
            'skill_4': 'Absorption',
            'skill_5': 'Baneful Focus'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Treznor' : {
        'name': 'Treznor',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Control',
        'img': 'images\\heroes\\Treznor.png',
        'sig_img': 'images\\items\\Treznor sigitem.png',
        'sig': 'Blade Of Promise',
        'skills': {
            'skill_1': 'Purging Cleave',
            'skill_2': 'Death Charge',
            'skill_3': 'Spear of Valor',
            'skill_4': 'Soul Barricade',
            'skill_5': 'Oath of Faith'
        },
        'background': '#026B5C',
        'rarity': 'Ascended',
    },
    'Ukyo' : {
        'name': 'Ukyo',
        'fac': 'Dimensional',
        'fac_img': 'images\\factions\\dimensional.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Ukyo.png',
        'sig_img': 'images\\items\\Ukyo sigitem.png',
        'sig': 'Nameless Self-Made Sword',
        'skills': {
            'skill_1': 'Hientorajin',
            'skill_2': 'Snowfall Slash',
            'skill_3': 'Phantom Strike',
            'skill_4': 'Swallow Swipe',
            'skill_5': 'Rage Eruption'
        },
        'background': '#1F75FE',
        'rarity': 'Ascended',
    },
    'Ulmus' : {
        'name': 'Ulmus',
        'fac': 'Wilder',
        'fac_img': 'images\\factions\\wilder.png',
        'role': 'Tank',
        'img': 'images\\heroes\\Ulmus.png',
        'sig_img': 'images\\items\\Ulmus sigitem.png',
        'sig': 'Totem Scoring',
        'skills': {
            'skill_1': 'Deep Roots',
            'skill_2': 'Writhing Roots',
            'skill_3': 'Forests Oath',
            'skill_4': 'Life Torrent',
            'skill_5': 'Healing Roots'
        },
        'background': '#779A71',
        'rarity': 'Ascended',
    },
    'Ulric' : {
        'name': 'Ulric',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Buffer',
        'img': 'images\\heroes\\Ulric.png',
        'sig_img': 'images\\items\\Ulric sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Knockback',
            'skill_2': 'Guard',
            'skill_3': '',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#FFFFFF',
        'rarity': 'Common',
    },
    'Vedan' : {
        'name': 'Vedan',
        'fac': 'Graveborn',
        'fac_img': 'images\\factions\\graveborn.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Vedan.png',
        'sig_img': 'images\\items\\Vedan sigitem.png',
        'sig': '',
        'skills': {
            'skill_1': 'Dark Swarm',
            'skill_2': 'Vitality',
            'skill_3': 'Thirst',
            'skill_4': '',
            'skill_5': ''
        },
        'background': '#026B5C',
        'rarity': 'Legendary',
    },
    'Vurk' : {
        'name': 'Vurk',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Aoe',
        'img': 'images\\heroes\\Vurk.png',
        'sig_img': 'images\\items\\Vurk sigitem.png',
        'sig': 'Shadow Stinger',
        'skills': {
            'skill_1': 'Mania',
            'skill_2': 'Piercing Bolt',
            'skill_3': 'Poison Vial',
            'skill_4': 'Poison Traps',
            'skill_5': 'Madness'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Walker' : {
        'name': 'Walker',
        'fac': 'Lightbearer',
        'fac_img': 'images\\factions\\lightbearer.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Walker.png',
        'sig_img': 'images\\items\\Walker sigitem.png',
        'sig': 'Ragin Bull',
        'skills': {
            'skill_1': 'Saloon Blast',
            'skill_2': 'Spittoon Smack',
            'skill_3': 'Gunslinger',
            'skill_4': 'Old Faithful',
            'skill_5': 'Hotshot'
        },
        'background': '#FFFFFF',
        'rarity': 'Ascended',
    },
    'Warek' : {
        'name': 'Warek',
        'fac': 'Mauler',
        'fac_img': 'images\\factions\\mauler.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Warek.png',
        'sig_img': 'images\\items\\Warek sigitem.png',
        'sig': 'Coward Crusher',
        'skills': {
            'skill_1': 'Bloodlust',
            'skill_2': 'Bonebreaker',
            'skill_3': 'Extricate',
            'skill_4': 'Carnal Rage',
            'skill_5': 'Brawlers Resistance'
        },
        'background': '#FF0000',
        'rarity': 'Ascended',
    },
    'Wu Kong' : {
        'name': 'Wu Kong',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Wu Kong.png',
        'sig_img': 'images\\items\\Wu Kong sigitem.png',
        'sig': 'The Golden Rod',
        'skills': {
            'skill_1': 'Cloud Clones',
            'skill_2': 'Bludgeon',
            'skill_3': 'Falling Fury',
            'skill_4': 'Foresight',
            'skill_5': 'Golden Barrier'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Zaphrael' : {
        'name': 'Zaphrael',
        'fac': 'Celestial',
        'fac_img': 'images\\factions\\celestial.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Zaphrael.png',
        'sig_img': 'images\\items\\Zaphrael sigitem.png',
        'sig': 'Arc Of Justice',
        'skills': {
            'skill_1': 'Lightning Purge',
            'skill_2': 'Thunderstorm',
            'skill_3': 'Lightning Arc',
            'skill_4': 'Static Charge',
            'skill_5': 'Zeal'
        },
        'background': '#F2E297',
        'rarity': 'Ascended',
    },
    'Zikis' : {
        'name': 'Zikis',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Continuous Damage',
        'img': 'images\\heroes\\Zikis.png',
        'sig_img': 'images\\items\\Zikis sigitem.png',
        'sig': 'Wings Of Lethargy',
        'skills': {
            'skill_1': 'Burning Sight',
            'skill_2': 'Corrosive Indolence',
            'skill_3': 'Languid Eye',
            'skill_4': 'Hatred',
            'skill_5': 'Bewilderment'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Zolrath' : {
        'name': 'Zolrath',
        'fac': 'Hypogean',
        'fac_img': 'images\\factions\\hypogean.png',
        'role': 'Assassin',
        'img': 'images\\heroes\\Zolrath.png',
        'sig_img': 'images\\items\\Zolrath sigitem.png',
        'sig': 'Hourglass Of Time',
        'skills': {
            'skill_1': 'Time Rift',
            'skill_2': 'Doppelganger',
            'skill_3': 'Annihilate',
            'skill_4': 'Déjà vu',
            'skill_5': 'Prey'
        },
        'background': '#712F85',
        'rarity': 'Ascended',
    },
    'Awakened Ezizh' : {
    'fac': 'Hypogean',
    'fac_img': 'AFK Compendium/images/factions/dimensional.png',
    'role': 'Continuous Damage',
    'img': 'AFK Compendium/images/heroes/awakened ezizh.png',
    'sig_img': 'AFK Compendium/images/items/awakened ezizh sigitem.png',
    'sig': 'Infernal Pauldron',
    'skills': {
        'skill_1': 'Nightmare's Descent',
        'skill_2': 'Dephts of Darkness',
        'skill_3': 'Mind Flay',
        'skill_4': 'Nightmare Arc',
        'skill_5': 'Dephts of Darkness'
        },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Awakened Talene' : {
    'fac': 'Celestial',
    'fac_img': 'AFK Compendium/images/factions/celestial.png',
    'role': 'Buffer',
    'img': 'AFK Compendium/images/heroes/awakened talene.png',
    'sig_img': 'AFK Compendium/images/items/awakened talene sigitem.png',
    'sig': 'Heart of the Phoenix',
    'skills': {
        'skill_1': 'A New Dawn',
        'skill_2': 'Blade of Resurgence',
        'skill_3': 'Everlasting Flame',
        'skill_4': 'Wings of Fire',
        'skill_5': 'Blade of Resurgence'
        },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Awakened Solise' : {
    'fac': 'Wilder',
    'fac_img': 'AFK Compendium/images/factions/wilder.png',
    'role': 'Regen',
    'img': 'AFK Compendium/images/heroes/awakened solise.png',
    'sig_img': 'AFK Compendium/images/items/awakened solise sigitem.png',
    'sig': 'Crescent Staff',
    'skills': {
        'skill_1': 'Clouds' Fall',
        'skill_2': 'Water's Call',
        'skill_3': 'Spirit Animation',
        'skill_4': 'Torrential Link',
        'skill_5': 'Water’s Call'
        },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Awakened Brutus' : {
    'fac': 'Mauler',
    'fac_img': 'AFK Compendium/images/factions/mauler.png',
    'role': 'Continuous Damage',
    'img': 'AFK Compendium/images/heroes/awakened brutus.png',
    'sig_img': 'AFK Compendium/images/items/awakened brutus sigitem.png',
    'sig': 'Montain Breaker',
    'skills': {
        'skill_1': 'Shattered Montain',
        'skill_2': 'Rank Breaker',
        'skill_3': 'Fury Blow',
        'skill_4': 'Unyielding Spirit',
        'skill_5': 'Rank Breaker'
        },
    'background': '#FF0000',
    'rarity': 'Ascended',
    },
    'Awakened Baden' : {
    'fac': 'Graveborn',
    'fac_img': 'AFK Compendium/images/factions/graveborn.png',
    'role': 'Continuous Damage',
    'img': 'AFK Compendium/images/heroes/awakened baden.png',
    'sig_img': 'AFK Compendium/images/items/awakened baden sigitem.png',
    'sig': 'Wilting Thorns',
    'skills': {
        'skill_1': 'Blight Clone',
        'skill_2': 'Razor Leaf',
        'skill_3': 'Vine Lash',
        'skill_4': 'Clone Link',
        'skill_5': 'Razor Leaf'
        },
    'background': '#026B5C',
    'rarity': 'Ascended',
    },
    'Awakened Thane' : {
    'fac': 'Lightbearer',
    'fac_img': 'AFK Compendium/images/factions/lightbearer.png',
    'role': 'Burst Damage',
    'img': 'AFK Compendium/images/heroes/awakened thane.png',
    'sig_img': 'AFK Compendium/images/items/awakened thane sigitem.png',
    'sig': 'The Lotus Blade',
    'skills': {
        'skill_1': 'Wind's Edge',
        'skill_2': 'Maelstrom',
        'skill_3': 'Dueling Blades',
        'skill_4': 'Winds of Fury',
        'skill_5': 'Maelstrom'
        },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Tarnos' : {
    'fac': 'Celestial',
    'fac_img': 'AFK Compendium/images/factions/celestial.png',
    'role': 'Continuous Damage',
    'img': 'AFK Compendium/images/heroes/tarnos.png',
    'sig_img': 'AFK Compendium/images/items/tarnos sigitem.png',
    'sig': 'Avenger’s Blade',
    'skills': {
        'skill_1': 'Atoner’s Prison',
        'skill_2': 'Oathbearer’s Strike',
        'skill_3': 'Divine Punishment',
        'skill_4': 'Pillars of Sin',
        'skill_5': 'Avenger’s Blade'
        },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Veithael' : {
    'fac': 'Celestial',
    'fac_img': 'AFK Compendium/images/factions/celestial.png',
    'role': 'Tank',
    'img': 'AFK Compendium/images/heroes/veithael.png',
    'sig_img': 'AFK Compendium/images/items/veithael sigitem.png',
    'sig': 'Resplendence',
    'skills': {
        'skill_1': 'Warmonger',
        'skill_2': 'Brutal Backswing',
        'skill_3': 'Hear No Evil',
        'skill_4': 'Head Held High',
        'skill_5': 'Godly Physique'
        },
    'background': '#F2E297',
    'rarity': 'Ascended',
    },
    'Vyloris' : {
    'fac': 'Hypogean',
    'fac_img': 'AFK Compendium/images/factions/hypogean.png',
    'role': 'Burst Damage',
    'img': 'AFK Compendium/images/heroes/vyloris.png',
    'sig_img': 'AFK Compendium/images/items/vyloris sigitem.png',
    'sig': 'Annulus of Lethality',
    'skills': {
        'skill_1': 'Cruel Endeavors',
        'skill_2': 'Cursed Agony',
        'skill_3': 'Fatal Embrace',
        'skill_4': 'Everlasting Torment',
        'skill_5': 'Havoc'
        },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Canisa and Ruke' : {
    'fac': 'Hypogean',
    'fac_img': 'AFK Compendium/images/factions/hypogean.png',
    'role': 'Tank',
    'img': 'AFK Compendium/images/heroes/canisa and ruke.png',
    'sig_img': 'AFK Compendium/images/items/canisa and ruke sigitem.png',
    'sig': 'Avenging Chain',
    'skills': {
        'skill_1': 'Lightning Lock',
        'skill_2': 'Wound Reversal',
        'skill_3': 'Howl of Fury',
        'skill_4': 'Cage of Fire',
        'skill_5': 'Chain Reach'
        },
    'background': '#712F85',
    'rarity': 'Ascended',
    },
    'Sonja' : {
    'fac': 'Lightbearer',
    'fac_img': 'AFK Compendium/images/factions/lightbearer.png',
    'role': 'Buffer',
    'img': 'AFK Compendium/images/heroes/sonja.png',
    'sig_img': 'AFK Compendium/images/items/sonja sigitem.png',
    'sig': 'The Lotus Blade',
    'skills': {
        'skill_1': 'Wind's Edge',
        'skill_2': 'Maelstrom',
        'skill_3': 'Dueling Blades',
        'skill_4': 'Winds of Fury',
        'skill_5': 'Maelstrom'
        },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Palmer' : {
    'fac': 'Lightbearer',
    'fac_img': 'AFK Compendium/images/factions/lightbearer.png',
    'role': 'Buffer',
    'img': 'AFK Compendium/images/heroes/palmer.png',
    'sig_img': 'AFK Compendium/images/items/palmer sigitem.png',
    'sig': 'The Lotus Blade',
    'skills': {
        'skill_1': 'Wind's Edge',
        'skill_2': 'Maelstrom',
        'skill_3': 'Dueling Blades',
        'skill_4': 'Winds of Fury',
        'skill_5': 'Maelstrom'
        },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Anasta' : {
    'fac': 'Mauler',
    'fac_img': 'AFK Compendium/images/factions/mauler.png',
    'role': 'Continuous Damage',
    'img': 'AFK Compendium/images/heroes/anasta.png',
    'sig_img': 'AFK Compendium/images/items/anasta sigitem.png',
    'sig': 'Windcleaver',
    'skills': {
        'skill_1': 'Spiral Cleaver',
        'skill_2': 'Confrontation',
        'skill_3': 'Shattered Shields',
        'skill_4': 'Mauler’s Prowess',
        'skill_5': 'Inextinguishable Might'
        },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Salaki' : {
    'fac': 'Mauler',
    'fac_img': 'AFK Compendium/images/factions/mauler.png',
    'role': 'Buffer',
    'img': 'AFK Compendium/images/heroes/salaki.png',
    'sig_img': 'AFK Compendium/images/items/salaki sigitem.png',
    'sig': 'Staff of Sacrifice',
    'skills': {
        'skill_1': 'Flagellant’s Flame',
        'skill_2': 'Withering Winds',
        'skill_3': 'Frightening Forcefield',
        'skill_4': 'Death Defferred',
        'skill_5': 'Inheritance'
        },
    'background': '#FFFFFF',
    'rarity': 'Ascended',
    },
    'Eorin' : {
    'fac': 'Wilder',
    'fac_img': 'AFK Compendium/images/factions/wilder.png',
    'role': 'Burst Damage',
    'img': 'AFK Compendium/images/heroes/eorin.png',
    'sig_img': 'AFK Compendium/images/items/eorin sigitem.png',
    'sig': 'Parasitic Spear',
    'skills': {
        'skill_1': 'Combined Spear',
        'skill_2': 'Weakspot Mark',
        'skill_3': 'Poisonous Mushroom',
        'skill_4': 'Stacking Spores',
        'skill_5': 'Parasitic Spear'
        },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Nevanthi' : {
    'fac': 'Wilder',
    'fac_img': 'AFK Compendium/images/factions/wilder.png',
    'role': 'Regen',
    'img': 'AFK Compendium/images/heroes/nevanthi.png',
    'sig_img': 'AFK Compendium/images/items/nevanthi sigitem.png',
    'sig': 'Deflecting Sprouts',
    'skills': {
        'skill_1': 'Nature’s Flourish',
        'skill_2': 'Connecting Branches',
        'skill_3': 'Natural Gifts',
        'skill_4': 'Verdant Shade',
        'skill_5': 'Deflecting Sprouts'
        },
    'background': '#779A71',
    'rarity': 'Ascended',
    },
    'Kalene' : {
    'fac': 'Graveborn',
    'fac_img': 'AFK Compendium/images/factions/graveborn.png',
    'role': 'Continuous Damage',
    'img': 'AFK Compendium/images/heroes/kalene.png',
    'sig_img': 'AFK Compendium/images/items/kalene sigitem.png',
    'sig': 'Necrohound',
    'skills': {
        'skill_1': 'Necrohound',
        'skill_2': 'Eternal Lifeblood',
        'skill_3': 'Ephemeral Spirits',
        'skill_4': 'Blood Ritual',
        'skill_5': 'Blood Feast'
        },
    'background': '#026B5C',
    'rarity': 'Ascended',
    }
}
